export type WelcomeButton = { id: string; label: string; url: string };
export type WelcomeBlock = { id: string; type: 'welcome'; enabled: boolean; text: string; returnText?: string; imageUrl?: string; buttons?: WelcomeButton[]; autoDeleteSeconds?: number; deleteJoinMessage?: boolean; firstJoinOnly?: boolean; skipBots?: boolean; skipAdmins?: boolean };
export type CaptchaBlock = { id: string; type: 'captcha'; enabled: boolean; text: string; buttonText: string; timeoutSeconds: number; failureAction: 'kick' | 'restrict'; deleteOnSuccess: boolean; skipBots: boolean; skipAdmins: boolean; skipTrusted: boolean };
export type AntiSpamBlock = { id: string; type: 'antispam'; enabled: boolean; floodEnabled: boolean; maxMessages: number; windowSeconds: number; duplicateEnabled: boolean; maxDuplicates: number; duplicateWindowSeconds: number; linksMode: 'allow' | 'block_all' | 'allowlist'; allowedDomains: string[]; action: 'delete' | 'delete_warn'; skipBots: boolean; skipAdmins: boolean; skipTrusted: boolean };
export type TextFilterCategory = { id: string; name: string; enabled: boolean; severity: 'standard' | 'serious' | 'critical'; terms: string[]; action: 'delete' | 'delete_warn'; responseMode: 'none' | 'custom'; responseText: string; autoDeleteSeconds: number };
export type ContentFiltersBlock = { id: string; type: 'content_filters'; enabled: boolean; stopWords: string[]; textCategories: TextFilterCategory[]; regexPatterns: string[]; blacklistedDomains: string[]; maxMentions: number; capsEnabled: boolean; capsPercent: number; capsMinLetters: number; emojiEnabled: boolean; maxEmoji: number; blockForwarded: boolean; blockedMedia: Array<'photo' | 'video' | 'document' | 'audio' | 'voice' | 'video_note' | 'sticker' | 'animation' | 'poll' | 'contact' | 'location'>; action: 'delete' | 'delete_warn'; skipBots: boolean; skipAdmins: boolean; skipTrusted: boolean };
export type ModeratorPersonality = { archetype:'calm'|'strict'|'insider'|'ironic'|'security'; character:string[]; manner:string[]; strictness:0|1|2|3; humor:0|1|2; slang:boolean; customInstructions:string };
export type AiModerationBlock = { id: string; type: 'ai_moderation'; enabled: boolean; rules: string; confidenceThreshold: number; action: 'review' | 'delete' | 'delete_warn'; minLength: number; skipBots: boolean; skipAdmins: boolean; skipTrusted: boolean; interventionsEnabled: boolean; interventionMode: 'observe' | 'respond' | 'respond_warn'; interventionScenarios: string[]; contextMessages: number; triggerAfterMessages: number; cooldownSeconds: number; maxInterventionsPerHour: number; interventionTone: 'channel' | 'friendly' | 'neutral' | 'strict'; responseAutoDeleteSeconds: number; repeatAction: 'nothing' | 'warn'; personality:ModeratorPersonality } ;
export type WarningPolicyBlock = { id: string; type: 'warning_policy'; enabled: boolean; warningExpiryDays: number; muteAfterWarnings: number; muteDurationSeconds: number; banAfterWarnings: number; deleteCommandMessages: boolean; notifyUser: boolean; skipAdmins: boolean };
export type TriggerButton = { id: string; label: string; url: string };
export type TriggerReply = { id: string; name: string; enabled: boolean; phrases: string[]; matchMode: 'exact' | 'prefix' | 'contains'; text: string; imageUrl?: string; buttons: TriggerButton[]; access: 'all' | 'admins'; cooldownSeconds: number; autoDeleteSeconds: number; deleteTriggerMessage: boolean; useAsAiKnowledge: boolean };
export type TriggersBlock = { id: string; type: 'triggers'; enabled: boolean; skipBots: boolean; triggers: TriggerReply[] };
export type ModeratorBlock = WelcomeBlock | CaptchaBlock | AntiSpamBlock | ContentFiltersBlock | WarningPolicyBlock | AiModerationBlock | TriggersBlock;

export const DEFAULT_BLOCKS: ModeratorBlock[] = [
  { id: 'welcome-default', type: 'welcome', enabled: false, text: 'Добро пожаловать, **{name}**! Перед общением познакомьтесь с правилами {group}.', buttons: [], autoDeleteSeconds: 0, deleteJoinMessage: false, firstJoinOnly: false, skipBots: true, skipAdmins: true },
  { id: 'captcha-default', type: 'captcha', enabled: false, text: '**{name}**, подтвердите, что вы человек.', buttonText: 'Я человек', timeoutSeconds: 300, failureAction: 'kick', deleteOnSuccess: true, skipBots: true, skipAdmins: true, skipTrusted: true },
  { id: 'content-filters-default', type: 'content_filters', enabled: false, stopWords: [], textCategories: [], regexPatterns: [], blacklistedDomains: [], maxMentions: 0, capsEnabled: false, capsPercent: 80, capsMinLetters: 10, emojiEnabled: false, maxEmoji: 10, blockForwarded: false, blockedMedia: [], action: 'delete', skipBots: true, skipAdmins: true, skipTrusted: true },
  { id: 'ai-moderation-default', type: 'ai_moderation', enabled: false, rules: 'Удалять явный спам, мошенничество, травлю и сообщения не по теме сообщества.', confidenceThreshold: 0.85, action: 'review', minLength: 8, skipBots: true, skipAdmins: true, skipTrusted: true, interventionsEnabled: false, interventionMode: 'observe', interventionScenarios: ['off_topic','politics','conflict','harassment'], contextMessages: 12, triggerAfterMessages: 3, cooldownSeconds: 600, maxInterventionsPerHour: 3, interventionTone: 'channel', responseAutoDeleteSeconds: 600, repeatAction: 'warn', personality:{archetype:'calm',character:['спокойный','справедливый'],manner:['коротко','по делу'],strictness:2,humor:0,slang:false,customInstructions:''} },
  { id: 'warning-policy-default', type: 'warning_policy', enabled: true, warningExpiryDays: 30, muteAfterWarnings: 3, muteDurationSeconds: 3600, banAfterWarnings: 5, deleteCommandMessages: true, notifyUser: true, skipAdmins: true },
  { id: 'antispam-default', type: 'antispam', enabled: false, floodEnabled: true, maxMessages: 6, windowSeconds: 10, duplicateEnabled: true, maxDuplicates: 3, duplicateWindowSeconds: 60, linksMode: 'allow', allowedDomains: [], action: 'delete', skipBots: true, skipAdmins: true, skipTrusted: true },
  { id: 'triggers-default', type: 'triggers', enabled: false, skipBots: true, triggers: [] },
];

const bool = (v: unknown, fallback: boolean) => typeof v === 'boolean' ? v : fallback;
const integer = (v: unknown, fallback: number, min: number, max: number) => Math.max(min, Math.min(Number.isInteger(v) ? Number(v) : fallback, max));
const normalizeDomains = (raw: unknown) => [...new Set((Array.isArray(raw) ? raw : []).flatMap(v => typeof v === 'string' ? [v.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0] ?? ''] : []).filter(Boolean))].slice(0, 100);
const MEDIA_TYPES = new Set(['photo','video','document','audio','voice','video_note','sticker','animation','poll','contact','location']);
const safeRegexPatterns = (raw: unknown): string[] => (Array.isArray(raw) ? raw : []).slice(0, 20).map((v, i) => { const pattern = typeof v === 'string' ? v.trim() : ''; if (!pattern) return ''; const unbounded = (pattern.match(/[*+]/g)?.length ?? 0) + (pattern.match(/\{\d+,\}/g)?.length ?? 0); const oversizedRange = [...pattern.matchAll(/\{(\d+)(?:,(\d*))?\}/g)].some(m => Number(m[1]) > 100 || (m[2] && Number(m[2]) > 100)); if (pattern.length > 120 || /\\[1-9]/.test(pattern) || /\(\?[=!<]/.test(pattern) || /\([^)]*[*+?{][^)]*\)[*+?{]/.test(pattern) || /\([^)]*\|[^)]*\)[*+?{]/.test(pattern) || unbounded > 1 || oversizedRange) throw new Error(`Небезопасное regex-выражение в строке ${i + 1}`); try { new RegExp(pattern, 'iu'); } catch { throw new Error(`Некорректное regex-выражение в строке ${i + 1}`); } return pattern; }).filter(Boolean);
const idAndEnabled = (b: Record<string, unknown>, index: number) => { if (typeof b['id'] !== 'string' || !b['id']) throw new Error(`blocks[${index}].id is required`); if (typeof b['enabled'] !== 'boolean') throw new Error(`blocks[${index}].enabled must be boolean`); return { id: b['id'], enabled: b['enabled'] }; };
const textList=(value:unknown,fallback:string[],max=5)=>Array.isArray(value)?[...new Set(value.flatMap(item=>typeof item==='string'&&item.trim()?[item.trim().slice(0,60)]:[]))].slice(0,max):fallback;
const moderatorPersonality=(value:unknown):ModeratorPersonality=>{
  const p=value&&typeof value==='object'?value as Record<string,unknown>:{},archetype=['calm','strict','insider','ironic','security'].includes(String(p['archetype']))?String(p['archetype']) as ModeratorPersonality['archetype']:'calm';
  return {archetype,character:textList(p['character'],['спокойный','справедливый']),manner:textList(p['manner'],['коротко','по делу']),strictness:integer(p['strictness'],2,0,3) as 0|1|2|3,humor:integer(p['humor'],0,0,2) as 0|1|2,slang:bool(p['slang'],false),customInstructions:typeof p['customInstructions']==='string'?p['customInstructions'].trim().slice(0,600):''};
};


export function parseBlocks(value: unknown): ModeratorBlock[] {
  if (!Array.isArray(value)) throw new Error('blocks must be an array');
  return value.map((raw, index) => {
    if (!raw || typeof raw !== 'object') throw new Error(`blocks[${index}] must be an object`);
    const b = raw as Record<string, unknown>; const base = idAndEnabled(b, index);
    if (b['type'] === 'triggers') {
      const triggers = (Array.isArray(b['triggers']) ? b['triggers'] : []).slice(0, 50).flatMap((rawTrigger, triggerIndex): TriggerReply[] => {
        if (!rawTrigger || typeof rawTrigger !== 'object') return [];
        const t = rawTrigger as Record<string, unknown>;
        const phrases = [...new Set((Array.isArray(t['phrases']) ? t['phrases'] : []).flatMap(v => typeof v === 'string' ? [v.trim().toLocaleLowerCase('ru-RU').replace(/\s+/g, ' ')] : []).filter(Boolean))].slice(0, 10).map(v => v.slice(0, 100));
        const text = typeof t['text'] === 'string' ? t['text'].trim().slice(0, 3500) : '';
        if (!phrases.length || !text) return [];
        const buttons = (Array.isArray(t['buttons']) ? t['buttons'] : []).slice(0, 3).flatMap((rawButton, buttonIndex): TriggerButton[] => {
          if (!rawButton || typeof rawButton !== 'object') return [];
          const q = rawButton as Record<string, unknown>, label = typeof q['label'] === 'string' ? q['label'].trim().slice(0, 64) : '', url = typeof q['url'] === 'string' ? q['url'].trim().slice(0, 2000) : '';
          return label && /^(https?:\/\/|tg:\/\/|@)/i.test(url) ? [{ id: typeof q['id'] === 'string' ? q['id'] : 'trigger-button-' + triggerIndex + '-' + buttonIndex, label, url }] : [];
        });
        return [{ id: typeof t['id'] === 'string' && t['id'] ? t['id'].slice(0, 100) : 'trigger-' + triggerIndex, name: (typeof t['name'] === 'string' && t['name'].trim() ? t['name'].trim() : phrases[0]!).slice(0, 80), enabled: bool(t['enabled'], true), phrases, matchMode: t['matchMode'] === 'prefix' || t['matchMode'] === 'contains' ? t['matchMode'] : 'exact', text, ...(typeof t['imageUrl'] === 'string' && /^https?:\/\//i.test(t['imageUrl']) ? { imageUrl: t['imageUrl'].slice(0, 2000) } : {}), buttons, access: t['access'] === 'admins' ? 'admins' : 'all', cooldownSeconds: integer(t['cooldownSeconds'], 30, 0, 3600), autoDeleteSeconds: integer(t['autoDeleteSeconds'], 0, 0, 172800), deleteTriggerMessage: bool(t['deleteTriggerMessage'], false), useAsAiKnowledge: bool(t['useAsAiKnowledge'], false) }];
      });
      return { ...base, type: 'triggers', skipBots: bool(b['skipBots'], true), triggers };
    }
    if (b['type'] === 'ai_moderation') return { ...base, type: 'ai_moderation', rules: (typeof b['rules'] === 'string' ? b['rules'].trim() : '').slice(0, 3000), confidenceThreshold: Math.max(0.5, Math.min(typeof b['confidenceThreshold'] === 'number' ? b['confidenceThreshold'] : 0.85, 0.99)), action: b['action'] === 'delete' || b['action'] === 'delete_warn' ? b['action'] : 'review', minLength: integer(b['minLength'], 8, 1, 500), skipBots: bool(b['skipBots'], true), skipAdmins: bool(b['skipAdmins'], true), skipTrusted: bool(b['skipTrusted'], true), interventionsEnabled: bool(b['interventionsEnabled'], false), interventionMode: b['interventionMode'] === 'respond' || b['interventionMode'] === 'respond_warn' ? b['interventionMode'] : 'observe', interventionScenarios: [...new Set((Array.isArray(b['interventionScenarios']) ? b['interventionScenarios'] : []).flatMap(v => typeof v === 'string' ? [v.slice(0, 64)] : []))].slice(0, 12), contextMessages: integer(b['contextMessages'], 12, 6, 20), triggerAfterMessages: integer(b['triggerAfterMessages'], 3, 2, 10), cooldownSeconds: integer(b['cooldownSeconds'], 600, 60, 3600), maxInterventionsPerHour: integer(b['maxInterventionsPerHour'], 3, 1, 20), interventionTone: b['interventionTone'] === 'friendly' || b['interventionTone'] === 'neutral' || b['interventionTone'] === 'strict' ? b['interventionTone'] : 'channel', responseAutoDeleteSeconds: integer(b['responseAutoDeleteSeconds'], 600, 0, 86400), repeatAction: b['repeatAction'] === 'nothing' ? 'nothing' : 'warn', personality:moderatorPersonality(b['personality']) };
    if (b['type'] === 'warning_policy') return { ...base, type: 'warning_policy', warningExpiryDays: integer(b['warningExpiryDays'], 30, 0, 365), muteAfterWarnings: integer(b['muteAfterWarnings'], 3, 0, 20), muteDurationSeconds: integer(b['muteDurationSeconds'], 3600, 60, 2592000), banAfterWarnings: integer(b['banAfterWarnings'], 5, 0, 50), deleteCommandMessages: bool(b['deleteCommandMessages'], true), notifyUser: bool(b['notifyUser'], true), skipAdmins: bool(b['skipAdmins'], true) };
    if (b['type'] === 'captcha') { const text = typeof b['text'] === 'string' ? b['text'].trim() : ''; if (!text) throw new Error(`blocks[${index}].text is required`); return { ...base, type: 'captcha', text: text.slice(0, 1000), buttonText: (typeof b['buttonText'] === 'string' && b['buttonText'].trim() ? b['buttonText'].trim() : 'Я человек').slice(0, 64), timeoutSeconds: integer(b['timeoutSeconds'], 300, 60, 1800), failureAction: b['failureAction'] === 'restrict' ? 'restrict' : 'kick', deleteOnSuccess: bool(b['deleteOnSuccess'], true), skipBots: bool(b['skipBots'], true), skipAdmins: bool(b['skipAdmins'], true), skipTrusted: bool(b['skipTrusted'], true) }; }
    if (b['type'] === 'content_filters') { const stopWords = [...new Set((Array.isArray(b['stopWords']) ? b['stopWords'] : []).flatMap(v => typeof v === 'string' ? v.split(/[\n,;\t]+/).map(item => item.trim().toLowerCase().replace(/\s+/g, ' ')) : []).filter(Boolean))].slice(0, 1000).map(v => v.slice(0, 64)); const textCategories = (Array.isArray(b['textCategories']) ? b['textCategories'] : []).slice(0, 20).flatMap((rawCategory, categoryIndex): TextFilterCategory[] => { if (!rawCategory || typeof rawCategory !== 'object') return []; const c = rawCategory as Record<string, unknown>; const terms = [...new Set((Array.isArray(c['terms']) ? c['terms'] : []).flatMap(v => typeof v === 'string' ? v.split(/[\n,;\t]+/).map(item => item.trim().toLowerCase().replace(/\s+/g, ' ')) : []).filter(Boolean))].slice(0, 1000).map(v => v.slice(0, 100)); if (!terms.length) return []; return [{ id: typeof c['id'] === 'string' && c['id'] ? c['id'].slice(0, 100) : 'filter-category-' + categoryIndex, name: (typeof c['name'] === 'string' && c['name'].trim() ? c['name'].trim() : 'Категория').slice(0, 80), enabled: bool(c['enabled'], true), severity: c['severity'] === 'serious' || c['severity'] === 'critical' ? c['severity'] : 'standard', terms, action: c['action'] === 'delete_warn' ? 'delete_warn' : 'delete', responseMode: c['responseMode'] === 'custom' ? 'custom' : 'none', responseText: (typeof c['responseText'] === 'string' ? c['responseText'].trim() : '').slice(0, 500), autoDeleteSeconds: integer(c['autoDeleteSeconds'], 0, 0, 86400) }]; }); const blockedMedia = [...new Set((Array.isArray(b['blockedMedia']) ? b['blockedMedia'] : []).flatMap(v => typeof v === 'string' && MEDIA_TYPES.has(v) ? [v] : []))] as ContentFiltersBlock['blockedMedia']; return { ...base, type: 'content_filters', stopWords, textCategories, regexPatterns: safeRegexPatterns(b['regexPatterns']), blacklistedDomains: normalizeDomains(b['blacklistedDomains']), maxMentions: integer(b['maxMentions'], 0, 0, 20), capsEnabled: bool(b['capsEnabled'], false), capsPercent: integer(b['capsPercent'], 80, 50, 100), capsMinLetters: integer(b['capsMinLetters'], 10, 5, 100), emojiEnabled: bool(b['emojiEnabled'], false), maxEmoji: integer(b['maxEmoji'], 10, 3, 50), blockForwarded: bool(b['blockForwarded'], false), blockedMedia, action: b['action'] === 'delete_warn' ? 'delete_warn' : 'delete', skipBots: bool(b['skipBots'], true), skipAdmins: bool(b['skipAdmins'], true), skipTrusted: bool(b['skipTrusted'], true) }; }
    if (b['type'] === 'antispam') { const rawDomains = Array.isArray(b['allowedDomains']) ? b['allowedDomains'] : []; const allowedDomains = [...new Set(rawDomains.flatMap(v => typeof v === 'string' ? [v.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0] ?? ''] : []).filter(Boolean))].slice(0, 100); return { ...base, type: 'antispam', floodEnabled: bool(b['floodEnabled'], true), maxMessages: integer(b['maxMessages'], 6, 3, 20), windowSeconds: integer(b['windowSeconds'], 10, 5, 60), duplicateEnabled: bool(b['duplicateEnabled'], true), maxDuplicates: integer(b['maxDuplicates'], 3, 2, 10), duplicateWindowSeconds: integer(b['duplicateWindowSeconds'], 60, 10, 300), linksMode: b['linksMode'] === 'block_all' || b['linksMode'] === 'allowlist' ? b['linksMode'] : 'allow', allowedDomains, action: b['action'] === 'delete_warn' ? 'delete_warn' : 'delete', skipBots: bool(b['skipBots'], true), skipAdmins: bool(b['skipAdmins'], true), skipTrusted: bool(b['skipTrusted'], true) }; }
    if (b['type'] !== 'welcome') throw new Error(`Unsupported block type: ${String(b['type'])}`);
    const text = typeof b['text'] === 'string' ? b['text'].trim() : ''; if (!text) throw new Error(`blocks[${index}].text is required`);
    const buttons = Array.isArray(b['buttons']) ? b['buttons'].slice(0, 3).flatMap((x, i) => { if (!x || typeof x !== 'object') return []; const q = x as Record<string, unknown>, label = typeof q['label'] === 'string' ? q['label'].trim().slice(0, 64) : '', url = typeof q['url'] === 'string' ? q['url'].trim().slice(0, 2000) : ''; return label && /^(https?:\/\/|@)/i.test(url) ? [{ id: typeof q['id'] === 'string' ? q['id'] : `welcome-btn-${i}`, label, url }] : []; }) : [];
    return { ...base, type: 'welcome', text: text.slice(0, 3500), ...(typeof b['returnText'] === 'string' && b['returnText'].trim() ? { returnText: b['returnText'].trim().slice(0, 3500) } : {}), ...(typeof b['imageUrl'] === 'string' && /^https?:\/\//i.test(b['imageUrl']) ? { imageUrl: b['imageUrl'].slice(0, 2000) } : {}), buttons, autoDeleteSeconds: integer(b['autoDeleteSeconds'], 0, 0, 172800), deleteJoinMessage: bool(b['deleteJoinMessage'], false), firstJoinOnly: bool(b['firstJoinOnly'], false), skipBots: bool(b['skipBots'], true), skipAdmins: bool(b['skipAdmins'], true) };
  });
}

export function requiredRightsFor(blocks: ModeratorBlock[]) {
  const welcome = blocks.find(b => b.type === 'welcome' && b.enabled) as WelcomeBlock | undefined;
  const captcha = blocks.find(b => b.type === 'captcha' && b.enabled);
  const antiSpam = blocks.find(b => b.type === 'antispam' && b.enabled);
  const filters = blocks.find(b => b.type === 'content_filters' && b.enabled);
  const aiModeration = blocks.find(b => b.type === 'ai_moderation' && b.enabled);
  const warningPolicy = blocks.find(b => b.type === 'warning_policy' && b.enabled);
  const triggers = blocks.find(b => b.type === 'triggers' && b.enabled) as TriggersBlock | undefined;
  const triggerDeletes = triggers?.triggers.some(t => t.enabled && (t.deleteTriggerMessage || t.autoDeleteSeconds));
  return { can_delete_messages: Boolean((welcome && (welcome.deleteJoinMessage || welcome.autoDeleteSeconds)) || captcha || antiSpam || filters || warningPolicy || aiModeration || triggerDeletes), can_restrict_members: Boolean(captcha || warningPolicy) };
}
