import type { GeneratedPost, PostVariant, Banner, LinkItem, SourceType, BrandKit } from '@/types'

const variantLabels = [
  ['Expert', 'Short', 'Founder Take'],
  ['News', 'Short', 'Promo'],
  ['Founder Take', 'Expert', 'Bold'],
]

function generateVariants(input: string, brandKit: BrandKit): PostVariant[] {
  const tone = brandKit.voiceProfile.tone
  const length = brandKit.voiceProfile.postLength
  const sig = brandKit.signature.text

  const labelSet = variantLabels[Math.floor(Math.random() * variantLabels.length)]

  const longText = `${input}

This is an insight worth sharing with the channel.

${tone === 'founder' ? 'Here\'s what we learned:' : 'Key takeaways:'}

→ Context matters more than tactics
→ ${length === 'long' ? 'Understanding the full picture before acting is what separates good decisions from reactive ones.' : 'Act on information, not noise.'}
→ The best time to start was yesterday. The second best is now.

${sig}`

  const shortText = `${input}

The key insight: timing and positioning beat effort every time.

${sig}`

  const founderText = `${input}

${tone === 'founder' || tone === 'bold' ? 'We\'ve been here before.' : 'Worth paying attention to.'}

The pattern is familiar. The response should be deliberate.

What does this mean for our space? More signal, less noise. That's the goal.

${sig}`

  return [
    { id: `v-${Date.now()}-a`, label: labelSet[0], text: longText, isSelected: true },
    { id: `v-${Date.now()}-b`, label: labelSet[1], text: shortText, isSelected: false },
    { id: `v-${Date.now()}-c`, label: labelSet[2], text: founderText, isSelected: false },
  ]
}

function generateBanner(title: string, brandKit: BrandKit): Banner {
  return {
    id: `b-${Date.now()}`,
    templateId: brandKit.visualKit.bannerTemplate,
    title,
    subtitle: 'Generated by Content Factory',
    accentColor: brandKit.visualKit.primaryColor,
    watermark: brandKit.visualKit.watermark,
  }
}

function extractTitle(input: string): string {
  const firstLine = input.split('\n')[0].trim()
  if (firstLine.length > 60) return firstLine.slice(0, 57) + '…'
  return firstLine || 'New Post'
}

export const generationService = {
  async generate(params: {
    input: string
    sourceType: SourceType
    channelId: string
    channelUsername: string
    brandKit: BrandKit
  }): Promise<GeneratedPost> {
    await new Promise(r => setTimeout(r, 1800))

    const { input, sourceType, channelId, channelUsername, brandKit } = params
    const title = extractTitle(input)
    const variants = generateVariants(input, brandKit)
    const banner = generateBanner(title, brandKit)

    const linkButtons: LinkItem[] = brandKit.linkKit.links.filter(
      l => l.usage === 'button' || l.usage === 'always'
    )

    return {
      id: `p-${Date.now()}`,
      title,
      sourceType,
      sourceSummary: input.slice(0, 120),
      channelId,
      channelUsername,
      variants,
      selectedVariantId: variants[0].id,
      banner,
      linkButtons,
      status: 'new',
      createdAt: new Date(),
    }
  },
}
