import { useCallback, useEffect, useState } from 'react'
import { ChevronDown, History, Loader2, RefreshCw, RotateCcw, ThumbsDown, ThumbsUp } from 'lucide-react'
import { API_BASE } from '@/lib/api'
import { getTelegramInitData, moderatorFetch } from '@/lib/telegram'
import { GlassCard } from '@/components/ui/GlassCard'
import { ModeratorHelpSheet, ModeratorInfoButton } from './ModeratorHelpSheet'

type Event = { id: string; tgUserId?: string | null; eventType: string; decision?: string | null; confidence?: number | null; reason?: string | null; action?: string | null; status: string; feedback?: string | null; reversedAt?: string | null; createdAt: string }
const labels: Record<string, string> = { AI_INTERVENTION: 'AI-вмешательство', AI_MODERATION_CHECKED: 'AI-проверка', AI_MODERATION_TRIGGERED: 'AI: нарушение', MANUAL_COMMAND: 'Ручное действие', ANTISPAM_TRIGGERED: 'Антиспам', ANTISPAM_EDITED: 'Антиспам изменения', CONTENT_FILTER_TRIGGERED: 'Фильтр контента', CONTENT_FILTER_EDITED: 'Фильтр изменения', MESSAGE_DISPOSITION: 'Результат обработки', TRIGGER_MATCHED: 'Триггер', CAPTCHA_PASSED: 'CAPTCHA пройдена', CAPTCHA_TIMEOUT: 'CAPTCHA: время истекло', SANCTION_EXPIRED: 'Санкция завершена', MEMBER_JOINED: 'Новый участник', PROBATION_TRIGGERED: 'Режим новичка', RAID_GUARD_TRIGGERED: 'Защита от рейда', RAID_DETECTED: 'Обнаружен рейд', GLOBAL_BLACKLIST: 'Чёрный список Publium', APPEAL: 'Апелляция участника' }
const AI_EVENTS = ['AI_INTERVENTION', 'AI_MODERATION_TRIGGERED']

export function ModerationLog({ communityId }: { communityId: string }) {
  const [events, setEvents] = useState<Event[]>([]), [loading, setLoading] = useState(false), [collapsed, setCollapsed] = useState(true), [busyId, setBusyId] = useState<string | null>(null), [error, setError] = useState(''), [helpOpen, setHelpOpen] = useState(false)
  const initData = getTelegramInitData()
  const load = useCallback(async () => { if (!initData) return; setLoading(true); try { const r = await moderatorFetch(`${API_BASE}/api/moderator/communities/${communityId}/events`); const d = await r.json() as { events?: Event[]; error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось загрузить журнал'); setEvents(d.events ?? []); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось загрузить журнал') } finally { setLoading(false) } }, [communityId, initData])
  useEffect(() => { if (!collapsed) void load() }, [collapsed, load])
  const reverse = async (event: Event) => { if (!initData || busyId) return; setBusyId(event.id); try { const r = await moderatorFetch(`${API_BASE}/api/moderator/communities/${communityId}/events/${event.id}/reverse`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось отменить'); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось отменить') } finally { setBusyId(null) } }
  const sendFeedback = async (event: Event, value: 'CONFIRMED' | 'FALSE_POSITIVE') => { if (!initData || busyId) return; setBusyId(event.id); try { const r = await moderatorFetch(`${API_BASE}/api/moderator/communities/${communityId}/events/${event.id}/feedback`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ value }) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось сохранить оценку'); setEvents(prev => prev.map(x => x.id === event.id ? { ...x, feedback: value } : x)) } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось сохранить оценку') } finally { setBusyId(null) } }
  return <GlassCard>
    <div className="flex items-center gap-1"><button type="button" aria-expanded={!collapsed} onClick={() => setCollapsed(v => !v)} className="flex min-h-14 min-w-0 flex-1 cursor-pointer items-center gap-3 rounded-[14px] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><span className="flex h-10 w-10 items-center justify-center rounded-[13px] bg-white/[0.05] text-[#8A8A93]"><History size={18} /></span><span className="min-w-0 flex-1"><span className="text-[14px] font-semibold text-white">Журнал модерации</span><span className="mt-0.5 block text-[11px] text-[#66666E]">Срабатывания, команды и отмена санкций</span></span><ChevronDown size={18} className={`text-[#66666E] transition-transform ${collapsed ? '-rotate-90' : ''}`} /></button><ModeratorInfoButton onClick={() => setHelpOpen(true)} label="Открыть справку: Журнал модерации" /></div>
    {!collapsed && <div className="mt-4"><div className="mb-3 flex items-center justify-between"><p className="text-[10px] uppercase tracking-wider text-[#66666E]">Последние 50 событий</p><button type="button" onClick={() => void load()} disabled={loading} aria-label="Обновить журнал" className="flex h-11 w-11 items-center justify-center rounded-[11px] text-[#777780] hover:bg-white/[0.06] hover:text-white"><RefreshCw size={15} className={loading ? 'animate-spin' : ''} /></button></div>
      {error && <p className="mb-3 rounded-[11px] bg-red-400/10 px-3 py-2 text-[11px] text-red-300">{error}</p>}
      {!loading && events.length === 0 ? <div className="rounded-[13px] border border-dashed border-white/[0.08] px-4 py-8 text-center text-[12px] text-[#66666E]">Событий пока нет</div> : <div className="space-y-2">{events.map(event => { const reversible = !event.reversedAt && Boolean(event.tgUserId) && ['WARN','DELETE_WARN','MUTE','BAN'].some(a => event.action?.includes(a)); const rateable = AI_EVENTS.includes(event.eventType) && !event.reversedAt; return <div key={event.id} className="rounded-[13px] border border-white/[0.06] bg-white/[0.025] p-3"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><p className="text-[12px] font-medium text-white">{labels[event.eventType] ?? event.eventType}</p>{event.reversedAt && <span className="rounded-full bg-white/[0.05] px-1.5 py-0.5 text-[9px] text-[#777780]">отменено</span>}{event.feedback === 'CONFIRMED' && <span className="rounded-full bg-emerald-400/10 px-1.5 py-0.5 text-[9px] text-emerald-300">верно</span>}{event.feedback === 'FALSE_POSITIVE' && <span className="rounded-full bg-amber-400/10 px-1.5 py-0.5 text-[9px] text-amber-300">ошибка AI</span>}</div><p className="mt-1 text-[11px] text-[#777780]">{event.decision || event.reason || event.action || 'Событие'}{event.tgUserId ? ` · ID ${event.tgUserId}` : ''}</p><p className="mt-1 text-[9px] text-[#55555D]">{new Date(event.createdAt).toLocaleString('ru-RU')}</p>{rateable && <div className="mt-2 flex gap-1.5"><button type="button" onClick={() => void sendFeedback(event, 'CONFIRMED')} disabled={busyId !== null} aria-label="Решение верное" className={`flex h-9 w-11 items-center justify-center rounded-[10px] border text-[#8A8A93] ${event.feedback === 'CONFIRMED' ? 'border-emerald-400/40 text-emerald-300' : 'border-white/[0.07] hover:text-emerald-300'}`}><ThumbsUp size={13} /></button><button type="button" onClick={() => void sendFeedback(event, 'FALSE_POSITIVE')} disabled={busyId !== null} aria-label="Решение ошибочное" className={`flex h-9 w-11 items-center justify-center rounded-[10px] border text-[#8A8A93] ${event.feedback === 'FALSE_POSITIVE' ? 'border-amber-400/40 text-amber-300' : 'border-white/[0.07] hover:text-amber-300'}`}><ThumbsDown size={13} /></button></div>}</div>{reversible && <button type="button" onClick={() => void reverse(event)} disabled={busyId !== null} aria-label="Отменить санкцию" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-[11px] border border-white/[0.07] text-[#8A8A93] hover:border-[rgba(255,106,0,0.25)] hover:text-[#FF6A00]">{busyId === event.id ? <Loader2 size={15} className="animate-spin" /> : <RotateCcw size={15} />}</button>}</div></div> })}</div>}
    </div>}
    <ModeratorHelpSheet kind="log" open={helpOpen} onClose={() => setHelpOpen(false)} />
  </GlassCard>
}
