import { useCallback, useEffect, useState } from 'react'
import { Activity, BrainCircuit, Check, ChevronDown, FlaskConical, Loader2, MessageCircle, Save, ShieldCheck } from 'lucide-react'
import { API_BASE } from '@/lib/api'
import { getTelegramInitData, moderatorFetch } from '@/lib/telegram'
import { GlassCard } from '@/components/ui/GlassCard'
import { Button } from '@/components/ui/Button'
import { Switch } from '@/components/ui/Switch'
import { ModeratorHelpSheet, ModeratorInfoButton } from './ModeratorHelpSheet'

type Personality={archetype:'calm'|'strict'|'insider'|'ironic'|'security';character:string[];manner:string[];strictness:0|1|2|3;humor:0|1|2;slang:boolean;customInstructions:string}
type AiBlock={id:string;type:'ai_moderation';enabled:boolean;rules:string;confidenceThreshold:number;action:'review'|'delete'|'delete_warn'|'delete_rewrite'|'delete_rewrite_warn';minLength:number;skipBots:boolean;skipAdmins:boolean;skipTrusted:boolean;interventionsEnabled:boolean;interventionMode:'observe'|'respond';responseAutoDeleteSeconds:number;personality:Personality}
type Simulation={intervene:boolean;category:string;severity:'low'|'medium'|'high';confidence:number;state:'OBSERVING'|'DEVELOPING'|'ESCALATING'|'RESOLVED';materialChange:boolean;reason:string;summary:string;response:string;participantIds:string[];actorIds:string[];targetIds:string[];riskDelta?:number}

const DEFAULT:AiBlock={id:'ai-moderation-default',type:'ai_moderation',enabled:false,rules:'Удалять явный мат, оскорбления, угрозы, травлю, спам, мошенничество и сообщения не по теме сообщества.',confidenceThreshold:.85,action:'review',minLength:1,skipBots:true,skipAdmins:true,skipTrusted:true,interventionsEnabled:false,interventionMode:'observe',responseAutoDeleteSeconds:600,personality:{archetype:'calm',character:['Спокойный','Справедливый'],manner:['Коротко','По делу'],strictness:2,humor:0,slang:false,customInstructions:''}}
const selectClass='mt-1.5 min-h-11 w-full cursor-pointer rounded-[11px] border border-white/[0.08] bg-[#171719] px-3 text-[13px] text-white outline-none transition-colors focus:border-[rgba(255,106,0,0.55)] focus-visible:ring-2 focus-visible:ring-[#FF6A00]/40'
const textareaClass='mt-1.5 w-full resize-none rounded-[12px] border border-white/[0.08] bg-[#0B0B0D] px-3.5 py-3 text-[13px] leading-relaxed text-white outline-none transition-colors focus:border-[rgba(255,106,0,0.55)] focus-visible:ring-2 focus-visible:ring-[#FF6A00]/30'
const stateLabel:Record<Simulation['state'],string>={OBSERVING:'Наблюдение',DEVELOPING:'Развивается',ESCALATING:'Эскалация',RESOLVED:'Завершён'}

export function ModeratorAiEditor({moderatorId}:{moderatorId:string}){
  const[block,setBlock]=useState(DEFAULT),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[publishing,setPublishing]=useState(false),[published,setPublished]=useState(false),[primaryCollapsed,setPrimaryCollapsed]=useState(false),[conversationCollapsed,setConversationCollapsed]=useState(false),[helpOpen,setHelpOpen]=useState(false),[message,setMessage]=useState(''),[simText,setSimText]=useState(''),[simulating,setSimulating]=useState(false),[simulation,setSimulation]=useState<Simulation|null>(null)
  const initData=getTelegramInitData()
  useEffect(()=>{if(!initData){setLoading(false);return}moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft`).then(async r=>{const d=await r.json() as{draft?:{blocks?:AiBlock[]};published?:{blocks?:AiBlock[]}|null;error?:string};if(!r.ok)throw new Error(d.error??'Не удалось загрузить AI');const found=d.draft?.blocks?.find(x=>x.type==='ai_moderation'),applied=d.published?.blocks?.find(x=>x.type==='ai_moderation');if(found)setBlock({...DEFAULT,...found,interventionMode:found.interventionMode==='respond'?'respond':'observe',personality:{...DEFAULT.personality,...found.personality}});const yes=Boolean(found&&applied&&JSON.stringify(found)===JSON.stringify(applied));setPublished(yes);if(yes){setPrimaryCollapsed(true);setConversationCollapsed(true)}}).catch(e=>setMessage(e instanceof Error?e.message:'Не удалось загрузить AI')).finally(()=>setLoading(false))},[initData,moderatorId])
  const save=useCallback(async()=>{if(!initData||!block.rules.trim())return false;setSaving(true);setMessage('');try{const r=await moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({blocks:[block]})}),d=await r.json() as{error?:string};if(!r.ok)throw new Error(d.error??'Не удалось сохранить');setMessage('Черновик сохранён');return true}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить');return false}finally{setSaving(false)}},[block,initData,moderatorId])
  const publish=async()=>{if(publishing)return;setPublishing(true);if(!await save()){setPublishing(false);return}try{const r=await moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/publish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({blockType:'ai_moderation'})}),d=await r.json() as{error?:string};if(!r.ok)throw new Error(d.error??'Не удалось применить');setPublished(true);setMessage('Настройки AI применены')}catch(e){setMessage(e instanceof Error?e.message:'Не удалось применить')}finally{setPublishing(false)}}
  const simulate=async()=>{if(!initData||simulating||simText.trim().length<10)return;setSimulating(true);setSimulation(null);try{const r=await moderatorFetch(`${API_BASE}/api/moderator/moderators/${moderatorId}/simulate-intervention`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation:simText})}),d=await r.json() as{decision?:Simulation;error?:string};if(!r.ok||!d.decision)throw new Error(d.error??'Terra не вернула решение');setSimulation(d.decision)}catch(e){setMessage(e instanceof Error?e.message:'Не удалось проверить')}finally{setSimulating(false)}}
  if(loading)return <div className="flex justify-center py-6 text-[#66666E]"><Loader2 size={20} className="animate-spin"/></div>
  const Header=({kind,collapsed,onToggle}:{kind:'primary'|'conversation';collapsed:boolean;onToggle:()=>void})=>{const primary=kind==='primary';return <div className={`flex items-center gap-1 ${collapsed?'':'mb-4'}`}><button type="button" aria-expanded={!collapsed} onClick={onToggle} className="flex min-h-14 min-w-0 flex-1 cursor-pointer items-center gap-3 rounded-[14px] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-[13px] ${primary?'bg-[rgba(255,106,0,0.10)] text-[#FF6A00]':'bg-cyan-400/10 text-cyan-300'}`}>{primary?<ShieldCheck size={18}/>:<MessageCircle size={18}/>}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-[14px] font-semibold text-white">{primary?'Первичная AI-модерация':'Разговорный интеллект'}{published&&<span className="flex items-center gap-1 text-[10px] font-normal text-emerald-400"><Check size={11}/> применено</span>}</span><span className="mt-0.5 block truncate text-[11px] text-[#777780]">{primary?'Одно сообщение · удаление и санкции':'Эпизоды · мягкое вмешательство без санкций'}</span></span><ChevronDown size={18} className={`shrink-0 text-[#66666E] transition-transform ${collapsed?'-rotate-90':''}`}/></button>{primary&&<ModeratorInfoButton onClick={()=>setHelpOpen(true)} label="Открыть справку: AI-модерация"/>}</div>}
  return <div className="space-y-3">
    <GlassCard><Header kind="primary" collapsed={primaryCollapsed} onToggle={()=>setPrimaryCollapsed(v=>!v)}/>{!primaryCollapsed&&<div>
      <div className="rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Проверять отдельные сообщения" description="Terra применяет выбранное ниже действие сразу после нарушения" value={block.enabled} onChange={enabled=>setBlock(p=>({...p,enabled}))}/></div>
      <label className="mt-4 block text-[11px] text-[#A1A1AA]" htmlFor="ai-rules">Что считается нарушением<textarea id="ai-rules" value={block.rules} onChange={e=>setBlock(p=>({...p,rules:e.target.value}))} rows={5} maxLength={3000} className={textareaClass}/></label>
      <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[11px] text-[#A1A1AA]">Уверенность<select value={block.confidenceThreshold} onChange={e=>setBlock(p=>({...p,confidenceThreshold:Number(e.target.value)}))} className={selectClass}>{[.7,.75,.8,.85,.9,.95].map(v=><option key={v} value={v}>{Math.round(v*100)}%</option>)}</select></label><label className="text-[11px] text-[#A1A1AA]">Проверять от<select value={block.minLength} onChange={e=>setBlock(p=>({...p,minLength:Number(e.target.value)}))} className={selectClass}>{[[1,'1 символа'],[3,'3 символов'],[5,'5 символов'],[8,'8 символов'],[15,'15 символов']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="col-span-2 text-[11px] text-[#A1A1AA]">Действие<select value={block.action} onChange={e=>setBlock(p=>({...p,action:e.target.value as AiBlock['action']}))} className={selectClass}><option value="review">Только журнал</option><option value="delete">Удалить + объяснить</option><option value="delete_warn">Удалить + warn</option><option value="delete_rewrite">Удалить + предложить культурную версию</option><option value="delete_rewrite_warn">Культурная версия + warn</option></select></label></div>
      {(block.action==='delete_rewrite'||block.action==='delete_rewrite_warn')&&<div className="mt-3 rounded-[12px] border border-emerald-400/15 bg-emerald-400/[0.05] px-3 py-2.5 text-[11px] leading-relaxed text-emerald-200/90">AI удалит нарушение и предложит культурную формулировку, сохранив факты, ссылки, числа и смысл.</div>}
      <div className="mt-4 space-y-3 rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Пропускать ботов" value={block.skipBots} onChange={skipBots=>setBlock(p=>({...p,skipBots}))}/><Switch label="Пропускать администраторов" value={block.skipAdmins} onChange={skipAdmins=>setBlock(p=>({...p,skipAdmins}))}/><Switch label="Пропускать доверенных" value={block.skipTrusted} onChange={skipTrusted=>setBlock(p=>({...p,skipTrusted}))}/></div>
    </div>}</GlassCard>

    <GlassCard><Header kind="conversation" collapsed={conversationCollapsed} onToggle={()=>setConversationCollapsed(v=>!v)}/>{!conversationCollapsed&&<div>
      <div className="rounded-[14px] border border-cyan-300/15 bg-cyan-300/[0.035] p-3"><Switch label="Анализировать развитие разговора" description="Terra связывает реплики в отдельные эпизоды конфликтов, травли и напряжения" value={block.interventionsEnabled} onChange={interventionsEnabled=>setBlock(p=>({...p,interventionsEnabled}))}/></div>
      {block.interventionsEnabled&&<div className="mt-4 space-y-4">
        <div className="grid grid-cols-2 gap-3"><label className="col-span-2 text-[11px] text-[#A1A1AA]">Режим<select value={block.interventionMode} onChange={e=>setBlock(p=>({...p,interventionMode:e.target.value as AiBlock['interventionMode']}))} className={selectClass}><option value="observe">Наблюдать и записывать в Pulse</option><option value="respond">Мягко вмешиваться при развитии</option></select></label></div>
        <div className="rounded-[13px] border border-white/[0.07] bg-black/20 p-3"><div className="flex items-start gap-2.5"><Activity size={16} className="mt-0.5 shrink-0 text-cyan-300"/><div><p className="text-[11px] font-semibold text-white">Адаптивный анализ</p><p className="mt-1 text-[11px] leading-relaxed text-[#A1A1AA]">Нет ручного контекста, пауз и лимита ответов. AI реагирует на изменение конкретного эпизода, а не на общий таймер чата. Удаления, warn, mute и ban остаются только в первичной модерации.</p></div></div></div>
        <details className="group rounded-[13px] border border-white/[0.07] bg-black/20"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between px-3 text-[11px] font-semibold text-white">Голос мягких ответов<ChevronDown size={14} className="text-[#66666E] transition-transform group-open:rotate-180"/></summary><div className="space-y-3 border-t border-white/[0.06] p-3"><label className="text-[11px] text-[#A1A1AA]">Роль<select value={block.personality.archetype} onChange={e=>setBlock(p=>({...p,personality:{...p.personality,archetype:e.target.value as Personality['archetype']}}))} className={selectClass}><option value="calm">Спокойный модератор</option><option value="strict">Строгий админ</option><option value="insider">Свой человек</option><option value="ironic">Ироничный модератор</option><option value="security">Сухой безопасник</option></select></label><div className="grid grid-cols-2 gap-3"><label className="text-[11px] text-[#A1A1AA]">Строгость<select value={block.personality.strictness} onChange={e=>setBlock(p=>({...p,personality:{...p.personality,strictness:Number(e.target.value) as 0|1|2|3}}))} className={selectClass}>{[['0','Мягкая'],['1','Спокойная'],['2','Уверенная'],['3','Жёсткая']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[11px] text-[#A1A1AA]">Ирония<select value={block.personality.humor} onChange={e=>setBlock(p=>({...p,personality:{...p.personality,humor:Number(e.target.value) as 0|1|2}}))} className={selectClass}><option value={0}>Без неё</option><option value={1}>Лёгкая</option><option value={2}>Заметная</option></select></label></div><Switch label="Разговорный сленг" description="Не используется при травле и высокой тяжести" value={block.personality.slang} onChange={slang=>setBlock(p=>({...p,personality:{...p.personality,slang}}))}/><label className="text-[11px] text-[#A1A1AA]" htmlFor="moderator-voice">Свои детали<textarea id="moderator-voice" rows={2} maxLength={600} value={block.personality.customInstructions} onChange={e=>setBlock(p=>({...p,personality:{...p.personality,customInstructions:e.target.value}}))} className={textareaClass} placeholder="Например: обращается «коллеги», без канцелярита"/></label></div></details>
        <div className="rounded-[13px] border border-white/[0.07] bg-black/20 p-3"><div className="flex items-center gap-2"><FlaskConical size={14} className="text-[#FF6A00]"/><p className="text-[11px] font-semibold text-white">Симулятор эпизода</p></div><textarea aria-label="Пример разговора" value={simText} onChange={e=>setSimText(e.target.value)} rows={5} placeholder={'Анна: Перестань переходить на личности\nИван: А ты мне не указывай\nАнна: Я говорю про аргументы'} className={textareaClass}/><Button variant="secondary" size="sm" fullWidth disabled={simulating||simText.trim().length<10} onClick={()=>void simulate()}>{simulating?<Loader2 size={14} className="animate-spin"/>:'Проанализировать эпизод'}</Button>{simulation&&<div className="mt-3 space-y-2 rounded-[11px] border border-white/[0.07] bg-white/[0.03] p-3"><div className="flex flex-wrap gap-2 text-[10px]"><span className="rounded-full bg-cyan-300/10 px-2 py-1 text-cyan-200">{stateLabel[simulation.state]}</span><span className="rounded-full bg-white/[0.06] px-2 py-1 text-[#D4D4D8]">{simulation.category} · {simulation.severity}</span><span className="rounded-full bg-white/[0.06] px-2 py-1 text-[#D4D4D8]">{Math.round(simulation.confidence*100)}%</span></div><p className="text-[11px] leading-relaxed text-[#A1A1AA]">{simulation.summary||simulation.reason}</p>{simulation.response&&<p className="text-[12px] leading-relaxed text-white">«{simulation.response}»</p>}<p className="text-[10px] text-[#777780]">Участники: {simulation.participantIds.length||'не определены'} · временный риск: +{simulation.riskDelta??0}</p></div>}</div>
      </div>}
      {message&&<p className="mt-3 text-[11px] text-[#A1A1AA]">{message}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" size="sm" onClick={()=>void save()} disabled={saving||publishing} fullWidth>{saving?<Loader2 size={14} className="animate-spin"/>:<><Save size={14}/> Сохранить</>}</Button><Button variant="primary" size="sm" onClick={()=>void publish()} disabled={saving||publishing} fullWidth>{publishing?<Loader2 size={14} className="animate-spin"/>:'Применить всё'}</Button></div>
    </div>}</GlassCard>
    <ModeratorHelpSheet kind="ai" open={helpOpen} onClose={()=>setHelpOpen(false)}/>
  </div>
}
