import { useCallback, useEffect, useState } from 'react'
import { BrainCircuit, Check, ChevronDown, Loader2, Save } from 'lucide-react'
import { API_BASE } from '@/lib/api'
import { getTelegramInitData } from '@/lib/telegram'
import { GlassCard } from '@/components/ui/GlassCard'
import { Button } from '@/components/ui/Button'
import { Switch } from '@/components/ui/Switch'
import { ModeratorHelpSheet, ModeratorInfoButton } from './ModeratorHelpSheet'

type AiBlock = { id: string; type: 'ai_moderation'; enabled: boolean; rules: string; confidenceThreshold: number; action: 'review' | 'delete' | 'delete_warn'; minLength: number; skipBots: boolean; skipAdmins: boolean; skipTrusted: boolean }
const DEFAULT: AiBlock = { id: 'ai-moderation-default', type: 'ai_moderation', enabled: false, rules: 'Удалять явный спам, мошенничество, травлю и сообщения не по теме сообщества.', confidenceThreshold: 0.85, action: 'review', minLength: 8, skipBots: true, skipAdmins: true, skipTrusted: true }
const selectClass = 'mt-1.5 min-h-11 w-full rounded-[11px] border border-white/[0.08] bg-[#171719] px-3 text-[13px] text-white outline-none focus:border-[rgba(255,106,0,0.45)]'

export function ModeratorAiEditor({ moderatorId }: { moderatorId: string }) {
  const [block, setBlock] = useState(DEFAULT), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [publishing, setPublishing] = useState(false), [published, setPublished] = useState(false), [collapsed, setCollapsed] = useState(false), [helpOpen, setHelpOpen] = useState(false), [message, setMessage] = useState('')
  const initData = getTelegramInitData()
  useEffect(() => { if (!initData) { setLoading(false); return } fetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft?initData=${encodeURIComponent(initData)}`).then(async r => { const d = await r.json() as { draft?: { blocks?: AiBlock[] }; moderator?: { publishedVersion?: number | null }; error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось загрузить AI'); const found = d.draft?.blocks?.find(x => x.type === 'ai_moderation'); if (found) setBlock({ ...DEFAULT, ...found }); const yes = Boolean(d.moderator?.publishedVersion); setPublished(yes); if (yes) setCollapsed(true) }).catch(e => setMessage(e instanceof Error ? e.message : 'Не удалось загрузить AI')).finally(() => setLoading(false)) }, [initData, moderatorId])
  const save = useCallback(async () => { if (!initData || !block.rules.trim()) return false; setSaving(true); setMessage(''); try { const r = await fetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ initData, blocks: [block] }) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось сохранить'); setMessage('Черновик сохранён'); return true } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось сохранить'); return false } finally { setSaving(false) } }, [block, initData, moderatorId])
  const publish = async () => { if (publishing) return; setPublishing(true); if (!await save()) { setPublishing(false); return } try { const r = await fetch(`${API_BASE}/api/moderator-config/${moderatorId}/publish`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ initData }) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось опубликовать'); setPublished(true); setMessage('AI-модерация опубликована') } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось опубликовать') } finally { setPublishing(false) } }
  if (loading) return <div className="flex justify-center py-6 text-[#66666E]"><Loader2 size={20} className="animate-spin" /></div>
  return <GlassCard>
    <div className={`flex items-center gap-1 ${collapsed ? '' : 'mb-4'}`}><button type="button" aria-expanded={!collapsed} onClick={() => setCollapsed(v => !v)} className="flex min-h-14 min-w-0 flex-1 items-center gap-3 rounded-[14px] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[13px] bg-[rgba(255,106,0,0.10)] text-[#FF6A00]"><BrainCircuit size={18} /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-[14px] font-semibold text-white">AI-модерация {published && <span className="flex items-center gap-1 text-[10px] font-normal text-emerald-400"><Check size={11} /> опубликовано</span>}</span><span className="mt-0.5 block truncate text-[11px] text-[#66666E]">{collapsed ? `${block.enabled ? 'Включена' : 'Выключена'} · Terra · ${Math.round(block.confidenceThreshold * 100)}%` : 'Контекстные нарушения по правилам канала'}</span></span><ChevronDown size={18} className={`shrink-0 text-[#66666E] transition-transform ${collapsed ? '-rotate-90' : ''}`} /></button><ModeratorInfoButton onClick={() => setHelpOpen(true)} label="Открыть справку: AI-модерация" /></div>
    {!collapsed && <div><div className="rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Включить Terra" description="Проверять сообщения после обычных фильтров" value={block.enabled} onChange={enabled => setBlock(p => ({ ...p, enabled }))} /></div>
      <label className="mt-4 block text-[11px] text-[#8A8A93]">Что считается нарушением<textarea value={block.rules} onChange={e => setBlock(p => ({ ...p, rules: e.target.value }))} rows={5} maxLength={3000} className="mt-1.5 w-full resize-none rounded-[12px] border border-white/[0.08] bg-[#0B0B0D] px-3.5 py-3 text-[13px] leading-relaxed text-white outline-none focus:border-[rgba(255,106,0,0.45)]" /></label>
      <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[11px] text-[#8A8A93]">Уверенность<select value={block.confidenceThreshold} onChange={e => setBlock(p => ({ ...p, confidenceThreshold: Number(e.target.value) }))} className={selectClass}>{[0.7,0.75,0.8,0.85,0.9,0.95].map(v => <option key={v} value={v}>{Math.round(v * 100)}%</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Действие<select value={block.action} onChange={e => setBlock(p => ({ ...p, action: e.target.value as AiBlock['action'] }))} className={selectClass}><option value="review">Только журнал</option><option value="delete">Удалить</option><option value="delete_warn">Удалить + warn</option></select></label></div>
      <div className="mt-4 rounded-[12px] border border-amber-400/15 bg-amber-400/[0.05] px-3 py-2.5 text-[11px] leading-relaxed text-amber-200/80">AI никогда не банит после одного сообщения. При ошибке или таймауте сообщение пропускается.</div>
      <div className="mt-4 space-y-3 rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Пропускать ботов" value={block.skipBots} onChange={skipBots => setBlock(p => ({ ...p, skipBots }))} /><Switch label="Пропускать администраторов" value={block.skipAdmins} onChange={skipAdmins => setBlock(p => ({ ...p, skipAdmins }))} /><Switch label="Пропускать доверенных" value={block.skipTrusted} onChange={skipTrusted => setBlock(p => ({ ...p, skipTrusted }))} /></div>
      {message && <p className="mt-3 text-[11px] text-[#8A8A93]">{message}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" size="sm" onClick={() => void save()} disabled={saving || publishing} fullWidth>{saving ? <Loader2 size={14} className="animate-spin" /> : <><Save size={14} /> Сохранить</>}</Button><Button variant="primary" size="sm" onClick={() => void publish()} disabled={saving || publishing} fullWidth>{publishing ? <Loader2 size={14} className="animate-spin" /> : 'Опубликовать'}</Button></div>
    </div>}
    <ModeratorHelpSheet kind="ai" open={helpOpen} onClose={() => setHelpOpen(false)} />
  </GlassCard>
}
