import { useCallback, useEffect, useState } from 'react'
import { BrainCircuit, Check, ChevronDown, FlaskConical, Loader2, Save } from 'lucide-react'
import { API_BASE } from '@/lib/api'
import { getTelegramInitData, moderatorFetch } from '@/lib/telegram'
import { GlassCard } from '@/components/ui/GlassCard'
import { Button } from '@/components/ui/Button'
import { Switch } from '@/components/ui/Switch'
import { ModeratorHelpSheet, ModeratorInfoButton } from './ModeratorHelpSheet'

type AiBlock = { id: string; type: 'ai_moderation'; enabled: boolean; rules: string; confidenceThreshold: number; action: 'review' | 'delete' | 'delete_warn'; minLength: number; skipBots: boolean; skipAdmins: boolean; skipTrusted: boolean; interventionsEnabled: boolean; interventionMode: 'observe' | 'respond' | 'respond_warn'; interventionScenarios: string[]; contextMessages: number; triggerAfterMessages: number; cooldownSeconds: number; maxInterventionsPerHour: number; interventionTone: 'channel' | 'friendly' | 'neutral' | 'strict'; responseAutoDeleteSeconds: number; repeatAction: 'nothing' | 'warn'; personality:{archetype:'calm'|'strict'|'insider'|'ironic'|'security';character:string[];manner:string[];strictness:0|1|2|3;humor:0|1|2;slang:boolean;customInstructions:string} }
const DEFAULT: AiBlock = { id: 'ai-moderation-default', type: 'ai_moderation', enabled: false, rules: 'Удалять явный спам, мошенничество, травлю и сообщения не по теме сообщества.', confidenceThreshold: 0.85, action: 'review', minLength: 8, skipBots: true, skipAdmins: true, skipTrusted: true, interventionsEnabled: false, interventionMode: 'observe', interventionScenarios: ['off_topic','politics','conflict','harassment'], contextMessages: 12, triggerAfterMessages: 3, cooldownSeconds: 600, maxInterventionsPerHour: 3, interventionTone: 'channel', responseAutoDeleteSeconds: 600, repeatAction: 'warn', personality:{archetype:'calm',character:['Спокойный','Справедливый'],manner:['Коротко','По делу'],strictness:2,humor:0,slang:false,customInstructions:''} }
const selectClass = 'mt-1.5 min-h-11 w-full rounded-[11px] border border-white/[0.08] bg-[#171719] px-3 text-[13px] text-white outline-none focus:border-[rgba(255,106,0,0.45)]'

export function ModeratorAiEditor({ moderatorId }: { moderatorId: string }) {
  const [block, setBlock] = useState(DEFAULT), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [publishing, setPublishing] = useState(false), [published, setPublished] = useState(false), [collapsed, setCollapsed] = useState(false), [helpOpen, setHelpOpen] = useState(false), [message, setMessage] = useState(''), [simText, setSimText] = useState(''), [simulating, setSimulating] = useState(false), [simulation, setSimulation] = useState<{ intervene:boolean; category:string; confidence:number; reason:string; response:string } | null>(null)
  const initData = getTelegramInitData()
  useEffect(() => { if (!initData) { setLoading(false); return } moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft`).then(async r => { const d = await r.json() as { draft?: { blocks?: AiBlock[] }; moderator?: { publishedVersion?: number | null }; error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось загрузить AI'); const found = d.draft?.blocks?.find(x => x.type === 'ai_moderation'); if (found) setBlock({ ...DEFAULT, ...found }); const yes = Boolean(d.moderator?.publishedVersion); setPublished(yes); if (yes) setCollapsed(true) }).catch(e => setMessage(e instanceof Error ? e.message : 'Не удалось загрузить AI')).finally(() => setLoading(false)) }, [initData, moderatorId])
  const save = useCallback(async () => { if (!initData || !block.rules.trim()) return false; setSaving(true); setMessage(''); try { const r = await moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ blocks: [block] }) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось сохранить'); setMessage('Черновик сохранён'); return true } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось сохранить'); return false } finally { setSaving(false) } }, [block, initData, moderatorId])
  const publish = async () => { if (publishing) return; setPublishing(true); if (!await save()) { setPublishing(false); return } try { const r = await moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/publish`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось применить'); setPublished(true); setMessage('AI-модерация применена') } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось применить') } finally { setPublishing(false) } }
  const simulate = async () => { if (!initData || simulating || simText.trim().length < 10) return; setSimulating(true); setSimulation(null); try { const r = await moderatorFetch(`${API_BASE}/api/moderator/moderators/${moderatorId}/simulate-intervention`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({conversation:simText}) }); const d=await r.json() as {decision?:typeof simulation;error?:string}; if(!r.ok||!d.decision) throw new Error(d.error ?? 'Terra не вернула решение'); setSimulation(d.decision) } catch(e) { setMessage(e instanceof Error?e.message:'Не удалось проверить') } finally { setSimulating(false) } }
  if (loading) return <div className="flex justify-center py-6 text-[#66666E]"><Loader2 size={20} className="animate-spin" /></div>
  return <GlassCard>
    <div className={`flex items-center gap-1 ${collapsed ? '' : 'mb-4'}`}><button type="button" aria-expanded={!collapsed} onClick={() => setCollapsed(v => !v)} className="flex min-h-14 min-w-0 flex-1 items-center gap-3 rounded-[14px] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[13px] bg-[rgba(255,106,0,0.10)] text-[#FF6A00]"><BrainCircuit size={18} /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-[14px] font-semibold text-white">AI-модерация {published && <span className="flex items-center gap-1 text-[10px] font-normal text-emerald-400"><Check size={11} /> применено</span>}</span><span className="mt-0.5 block truncate text-[11px] text-[#66666E]">{collapsed ? `${block.enabled ? 'Включена' : 'Выключена'} · Terra · ${Math.round(block.confidenceThreshold * 100)}%` : 'Контекстные нарушения по правилам канала'}</span></span><ChevronDown size={18} className={`shrink-0 text-[#66666E] transition-transform ${collapsed ? '-rotate-90' : ''}`} /></button><ModeratorInfoButton onClick={() => setHelpOpen(true)} label="Открыть справку: AI-модерация" /></div>
    {!collapsed && <div><div className="rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Включить Terra" description="Проверять сообщения после обычных фильтров" value={block.enabled} onChange={enabled => setBlock(p => ({ ...p, enabled }))} /></div>
      <label className="mt-4 block text-[11px] text-[#8A8A93]">Что считается нарушением<textarea value={block.rules} onChange={e => setBlock(p => ({ ...p, rules: e.target.value }))} rows={5} maxLength={3000} className="mt-1.5 w-full resize-none rounded-[12px] border border-white/[0.08] bg-[#0B0B0D] px-3.5 py-3 text-[13px] leading-relaxed text-white outline-none focus:border-[rgba(255,106,0,0.45)]" /></label>
      <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[11px] text-[#8A8A93]">Уверенность<select value={block.confidenceThreshold} onChange={e => setBlock(p => ({ ...p, confidenceThreshold: Number(e.target.value) }))} className={selectClass}>{[0.7,0.75,0.8,0.85,0.9,0.95].map(v => <option key={v} value={v}>{Math.round(v * 100)}%</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Действие<select value={block.action} onChange={e => setBlock(p => ({ ...p, action: e.target.value as AiBlock['action'] }))} className={selectClass}><option value="review">Только журнал</option><option value="delete">Удалить</option><option value="delete_warn">Удалить + warn</option></select></label></div>
      <details className="group mt-4 rounded-[14px] border border-[rgba(255,106,0,0.16)] bg-[rgba(255,106,0,0.035)]"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between px-3.5 text-[12px] font-semibold text-white">AI-вмешательства <ChevronDown size={15} className="text-[#66666E] transition-transform group-open:rotate-180" /></summary><div className="space-y-4 border-t border-white/[0.07] p-3">
        <Switch label="Следить за развитием разговора" description="Terra анализирует пакет сообщений и мягко вмешивается" value={block.interventionsEnabled} onChange={interventionsEnabled=>setBlock(p=>({...p,interventionsEnabled}))} />
        {block.interventionsEnabled&&<details className="group rounded-[13px] border border-white/[0.07] bg-black/20"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between px-3 text-[11px] font-semibold text-white">Образ Moderator <ChevronDown size={14} className="text-[#66666E] transition-transform group-open:rotate-180"/></summary><div className="space-y-3 border-t border-white/[0.06] p-3"><label className="text-[11px] text-[#8A8A93]">Роль<select value={block.personality.archetype} onChange={e=>setBlock(p=>({...p,personality:{...p.personality,archetype:e.target.value as AiBlock['personality']['archetype']}}))} className={selectClass}><option value="calm">Спокойный смотрящий</option><option value="strict">Строгий админ</option><option value="insider">Свой человек</option><option value="ironic">Ироничный смотрящий</option><option value="security">Сухой безопасник</option></select></label><div className="grid grid-cols-2 gap-3"><label className="text-[11px] text-[#8A8A93]">Строгость<select value={block.personality.strictness} onChange={e=>setBlock(p=>({...p,personality:{...p.personality,strictness:Number(e.target.value) as 0|1|2|3}}))} className={selectClass}>{[['0','Мягкая'],['1','Спокойная'],['2','Уверенная'],['3','Жёсткая']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Ирония<select value={block.personality.humor} onChange={e=>setBlock(p=>({...p,personality:{...p.personality,humor:Number(e.target.value) as 0|1|2}}))} className={selectClass}><option value={0}>Без неё</option><option value={1}>Лёгкая</option><option value={2}>Заметная</option></select></label></div><Switch label="Разговорный сленг" description="Только в мягких ситуациях; не в санкциях и травле" value={block.personality.slang} onChange={slang=>setBlock(p=>({...p,personality:{...p.personality,slang}}))}/><label className="text-[11px] text-[#8A8A93]">Свои детали<textarea rows={2} maxLength={600} value={block.personality.customInstructions} onChange={e=>setBlock(p=>({...p,personality:{...p.personality,customInstructions:e.target.value}}))} className="mt-1.5 w-full resize-none rounded-[11px] border border-white/[0.08] bg-[#0B0B0D] px-3 py-2.5 text-[12px] text-white outline-none focus:border-[rgba(255,106,0,0.45)]" placeholder="Например: обращается «коллеги», не использует канцелярит"/></label><p className="text-[10px] leading-relaxed text-[#66666E]">Образ меняет только формулировку. Правила, пороги и санкции остаются неизменными.</p></div></details>}
        {block.interventionsEnabled && <><div className="grid grid-cols-2 gap-3"><label className="text-[11px] text-[#8A8A93]">Режим<select value={block.interventionMode} onChange={e=>setBlock(p=>({...p,interventionMode:e.target.value as AiBlock['interventionMode']}))} className={selectClass}><option value="observe">Только наблюдать</option><option value="respond">Мягко отвечать</option><option value="respond_warn">Ответ + warn при повторе</option></select></label><label className="text-[11px] text-[#8A8A93]">Тон<select value={block.interventionTone} onChange={e=>setBlock(p=>({...p,interventionTone:e.target.value as AiBlock['interventionTone']}))} className={selectClass}><option value="channel">Стиль канала</option><option value="friendly">Дружелюбный</option><option value="neutral">Нейтральный</option><option value="strict">Строгий</option></select></label><label className="text-[11px] text-[#8A8A93]">Контекст<select value={block.contextMessages} onChange={e=>setBlock(p=>({...p,contextMessages:Number(e.target.value)}))} className={selectClass}>{[8,12,16,20].map(v=><option key={v} value={v}>{v} сообщений</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Проверять после<select value={block.triggerAfterMessages} onChange={e=>setBlock(p=>({...p,triggerAfterMessages:Number(e.target.value)}))} className={selectClass}>{[2,3,5,8,10].map(v=><option key={v} value={v}>{v} новых</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Пауза<select value={block.cooldownSeconds} onChange={e=>setBlock(p=>({...p,cooldownSeconds:Number(e.target.value)}))} className={selectClass}>{[[300,'5 мин.'],[600,'10 мин.'],[1200,'20 мин.'],[1800,'30 мин.'],[3600,'1 час']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Ответов в час<select value={block.maxInterventionsPerHour} onChange={e=>setBlock(p=>({...p,maxInterventionsPerHour:Number(e.target.value)}))} className={selectClass}>{[1,2,3,5,10].map(v=><option key={v} value={v}>{v}</option>)}</select></label></div>
        <div><p className="mb-2 text-[11px] text-[#8A8A93]">Следить за ситуациями</p><div className="flex flex-wrap gap-2">{[['off_topic','Оффтоп'],['politics','Политика'],['conflict','Конфликт'],['harassment','Травля'],['promotion','Реклама']].map(([id,label])=><button key={id} type="button" onClick={()=>setBlock(p=>({...p,interventionScenarios:p.interventionScenarios.includes(id)?p.interventionScenarios.filter(x=>x!==id):[...p.interventionScenarios,id]}))} className={`min-h-10 rounded-[10px] border px-3 text-[11px] ${block.interventionScenarios.includes(id)?'border-[rgba(255,106,0,0.28)] bg-[rgba(255,106,0,0.10)] text-[#FF8A3D]':'border-white/[0.07] text-[#777780]'}`}>{label}</button>)}</div></div>
        <div className="rounded-[13px] border border-white/[0.07] bg-black/20 p-3"><div className="flex items-center gap-2"><FlaskConical size={14} className="text-[#FF6A00]"/><p className="text-[11px] font-semibold text-white">Проверить на примере</p></div><textarea value={simText} onChange={e=>setSimText(e.target.value)} rows={5} placeholder={'Анна: Видели политические новости?\nИван: Да, я считаю...\nАнна: А вот вы все...'} className="mt-3 w-full resize-none rounded-[11px] border border-white/[0.08] bg-[#0B0B0D] px-3 py-2.5 text-[12px] leading-relaxed text-white outline-none"/><Button variant="secondary" size="sm" fullWidth disabled={simulating||simText.trim().length<10} onClick={()=>void simulate()}>{simulating?<Loader2 size={14} className="animate-spin"/>:'Запустить симуляцию'}</Button>{simulation&&<div className="mt-3 rounded-[11px] border border-white/[0.07] bg-white/[0.03] p-3"><p className="text-[11px] font-semibold text-white">{simulation.intervene?'Вмешаться':'Не вмешиваться'} · {Math.round(simulation.confidence*100)}%</p><p className="mt-1 text-[11px] text-[#777780]">{simulation.reason}</p>{simulation.response&&<p className="mt-2 text-[12px] leading-relaxed text-[#D4D4D8]">«{simulation.response}»</p>}</div>}</div></>}
      </div></details>
      <div className="mt-4 rounded-[12px] border border-amber-400/15 bg-amber-400/[0.05] px-3 py-2.5 text-[11px] leading-relaxed text-amber-200/80">AI никогда не банит после одного сообщения. При ошибке или таймауте сообщение пропускается.</div>
      <div className="mt-4 space-y-3 rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Пропускать ботов" value={block.skipBots} onChange={skipBots => setBlock(p => ({ ...p, skipBots }))} /><Switch label="Пропускать администраторов" value={block.skipAdmins} onChange={skipAdmins => setBlock(p => ({ ...p, skipAdmins }))} /><Switch label="Пропускать доверенных" value={block.skipTrusted} onChange={skipTrusted => setBlock(p => ({ ...p, skipTrusted }))} /></div>
      {message && <p className="mt-3 text-[11px] text-[#8A8A93]">{message}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" size="sm" onClick={() => void save()} disabled={saving || publishing} fullWidth>{saving ? <Loader2 size={14} className="animate-spin" /> : <><Save size={14} /> Сохранить</>}</Button><Button variant="primary" size="sm" onClick={() => void publish()} disabled={saving || publishing} fullWidth>{publishing ? <Loader2 size={14} className="animate-spin" /> : 'Применить'}</Button></div>
    </div>}
    <ModeratorHelpSheet kind="ai" open={helpOpen} onClose={() => setHelpOpen(false)} />
  </GlassCard>
}
