import { useCallback, useEffect, useState } from 'react'
import { Check, ChevronDown, ListFilter, Loader2, Save } from 'lucide-react'
import { API_BASE } from '@/lib/api'
import { getTelegramInitData } from '@/lib/telegram'
import { GlassCard } from '@/components/ui/GlassCard'
import { Button } from '@/components/ui/Button'
import { Switch } from '@/components/ui/Switch'
import { ModeratorHelpSheet, ModeratorInfoButton } from '@/components/moderator/ModeratorHelpSheet'

type MediaType = 'photo' | 'video' | 'document' | 'audio' | 'voice' | 'video_note' | 'sticker' | 'animation' | 'poll' | 'contact' | 'location'
type FiltersBlock = { id: string; type: 'content_filters'; enabled: boolean; stopWords: string[]; regexPatterns: string[]; blacklistedDomains: string[]; maxMentions: number; capsEnabled: boolean; capsPercent: number; capsMinLetters: number; emojiEnabled: boolean; maxEmoji: number; blockForwarded: boolean; blockedMedia: MediaType[]; action: 'delete' | 'delete_warn'; skipBots: boolean; skipAdmins: boolean; skipTrusted: boolean }
const DEFAULT: FiltersBlock = { id: 'content-filters-default', type: 'content_filters', enabled: false, stopWords: [], regexPatterns: [], blacklistedDomains: [], maxMentions: 0, capsEnabled: false, capsPercent: 80, capsMinLetters: 10, emojiEnabled: false, maxEmoji: 10, blockForwarded: false, blockedMedia: [], action: 'delete', skipBots: true, skipAdmins: true, skipTrusted: true }
const MEDIA: Array<{ id: MediaType; label: string }> = [{ id: 'photo', label: 'Фото' }, { id: 'video', label: 'Видео' }, { id: 'document', label: 'Файлы' }, { id: 'audio', label: 'Аудио' }, { id: 'voice', label: 'Голосовые' }, { id: 'video_note', label: 'Кружки' }, { id: 'sticker', label: 'Стикеры' }, { id: 'animation', label: 'GIF' }, { id: 'poll', label: 'Опросы' }, { id: 'contact', label: 'Контакты' }, { id: 'location', label: 'Геолокация' }]
const inputClass = 'mt-1.5 min-h-11 w-full rounded-[11px] border border-white/[0.08] bg-[#171719] px-3 text-[13px] text-white outline-none focus:border-[rgba(255,106,0,0.45)]'
const list = (value: string) => value.split(/\n+/).map(x => x.trim()).filter(Boolean)

export function ModeratorContentFiltersEditor({ moderatorId }: { moderatorId: string }) {
  const [block, setBlock] = useState(DEFAULT), [words, setWords] = useState(''), [patterns, setPatterns] = useState(''), [domains, setDomains] = useState('')
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [publishing, setPublishing] = useState(false), [published, setPublished] = useState(false), [collapsed, setCollapsed] = useState(false), [message, setMessage] = useState('')
  const [helpOpen, setHelpOpen] = useState(false)
  const initData = getTelegramInitData()
  useEffect(() => { if (!initData) { setLoading(false); return } fetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft?initData=${encodeURIComponent(initData)}`).then(async r => { const d = await r.json() as { draft?: { blocks?: FiltersBlock[] }; moderator?: { publishedVersion?: number | null }; error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось загрузить фильтры'); const found = d.draft?.blocks?.find(x => x.type === 'content_filters'); if (found) { setBlock({ ...DEFAULT, ...found }); setWords(found.stopWords.join('\n')); setPatterns(found.regexPatterns.join('\n')); setDomains(found.blacklistedDomains.join('\n')) } const yes = Boolean(d.moderator?.publishedVersion); setPublished(yes); if (yes) setCollapsed(true) }).catch(e => setMessage(e instanceof Error ? e.message : 'Не удалось загрузить фильтры')).finally(() => setLoading(false)) }, [initData, moderatorId])
  const save = useCallback(async () => { if (!initData) return false; setSaving(true); setMessage(''); const next = { ...block, stopWords: list(words), regexPatterns: list(patterns), blacklistedDomains: list(domains) }; try { const r = await fetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ initData, blocks: [next] }) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось сохранить'); setBlock(next); setMessage('Черновик сохранён'); return true } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось сохранить'); return false } finally { setSaving(false) } }, [block, domains, initData, moderatorId, patterns, words])
  const publish = async () => { if (!initData || publishing) return; setPublishing(true); if (!await save()) { setPublishing(false); return } try { const r = await fetch(`${API_BASE}/api/moderator-config/${moderatorId}/publish`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ initData }) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось опубликовать'); setPublished(true); setMessage('Фильтры опубликованы') } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось опубликовать') } finally { setPublishing(false) } }
  const toggleMedia = (id: MediaType) => setBlock(p => ({ ...p, blockedMedia: p.blockedMedia.includes(id) ? p.blockedMedia.filter(x => x !== id) : [...p.blockedMedia, id] }))
  if (loading) return <div className="flex justify-center py-6 text-[#66666E]"><Loader2 size={20} className="animate-spin" /></div>
  return <GlassCard>
    <div className={`flex items-center gap-1 ${collapsed ? '' : 'mb-4'}`}>
      <button type="button" aria-expanded={!collapsed} onClick={() => setCollapsed(v => !v)} className="flex min-h-14 min-w-0 flex-1 cursor-pointer items-center gap-3 rounded-[14px] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]">
        <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[13px] bg-[rgba(255,106,0,0.10)] text-[#FF6A00]"><ListFilter size={18} /></span>
        <span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-[14px] font-semibold text-white">Фильтры контента {published && <span className="flex items-center gap-1 text-[10px] font-normal text-emerald-400"><Check size={11} /> опубликовано</span>}</span><span className="mt-0.5 block truncate text-[11px] text-[#66666E]">{collapsed ? `${block.enabled ? 'Включены' : 'Выключены'} · текст · вложения` : 'Содержимое и тип отдельного сообщения'}</span></span>
        <ChevronDown size={18} className={`shrink-0 text-[#66666E] transition-transform ${collapsed ? '-rotate-90' : ''}`} />
      </button>
      <ModeratorInfoButton onClick={() => setHelpOpen(true)} label="Открыть справку: Фильтры контента" />
    </div>
    {!collapsed && <div>
      <div className="rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Включить фильтры" description="Проверять сообщения и их редактирование" value={block.enabled} onChange={enabled => setBlock(p => ({ ...p, enabled }))} /></div>
      <details open className="group mt-4 rounded-[14px] border border-white/[0.07] bg-white/[0.025]"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between px-3 text-[12px] font-semibold text-white">Текст и домены <ChevronDown size={15} className="text-[#66666E] transition-transform group-open:rotate-180" /></summary><div className="space-y-3 border-t border-white/[0.07] p-3"><label className="block text-[11px] text-[#8A8A93]">Стоп-слова и фразы<textarea value={words} onChange={e => setWords(e.target.value)} rows={4} placeholder={'спам\nзапрещённая фраза'} className={inputClass + ' py-2.5'} /></label><label className="block text-[11px] text-[#8A8A93]">Regex-паттерны<textarea value={patterns} onChange={e => setPatterns(e.target.value)} rows={3} placeholder={'\\bpromo[-_ ]?code\\b'} className={inputClass + ' py-2.5 font-mono'} /><span className="mt-1 block text-[10px] text-[#55555D]">По одному безопасному выражению на строку.</span></label><label className="block text-[11px] text-[#8A8A93]">Чёрный список доменов<textarea value={domains} onChange={e => setDomains(e.target.value)} rows={3} placeholder={'spam.example\nbad-site.com'} className={inputClass + ' py-2.5'} /></label></div></details>
      <details className="group mt-4 rounded-[14px] border border-white/[0.07] bg-white/[0.025]"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between px-3 text-[12px] font-semibold text-white">Поведение текста <ChevronDown size={15} className="text-[#66666E] transition-transform group-open:rotate-180" /></summary><div className="space-y-3 border-t border-white/[0.07] p-3"><label className="block text-[11px] text-[#8A8A93]">Максимум упоминаний<select value={block.maxMentions} onChange={e => setBlock(p => ({ ...p, maxMentions: Number(e.target.value) }))} className={inputClass}><option value={0}>Не ограничивать</option>{[1,2,3,5,10,20].map(v => <option key={v} value={v}>{v}</option>)}</select></label><Switch label="Ограничить CAPS" value={block.capsEnabled} onChange={capsEnabled => setBlock(p => ({ ...p, capsEnabled }))} />{block.capsEnabled && <div className="grid grid-cols-2 gap-3"><label className="text-[11px] text-[#8A8A93]">Процент<select value={block.capsPercent} onChange={e => setBlock(p => ({ ...p, capsPercent: Number(e.target.value) }))} className={inputClass}>{[50,60,70,80,90,100].map(v => <option key={v} value={v}>{v}%</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Минимум букв<select value={block.capsMinLetters} onChange={e => setBlock(p => ({ ...p, capsMinLetters: Number(e.target.value) }))} className={inputClass}>{[5,10,15,20,50,100].map(v => <option key={v} value={v}>{v}</option>)}</select></label></div>}<Switch label="Ограничить эмодзи" value={block.emojiEnabled} onChange={emojiEnabled => setBlock(p => ({ ...p, emojiEnabled }))} />{block.emojiEnabled && <label className="block text-[11px] text-[#8A8A93]">Максимум эмодзи<select value={block.maxEmoji} onChange={e => setBlock(p => ({ ...p, maxEmoji: Number(e.target.value) }))} className={inputClass}>{[3,5,10,15,20,30,50].map(v => <option key={v} value={v}>{v}</option>)}</select></label>}<Switch label="Запретить пересланные сообщения" value={block.blockForwarded} onChange={blockForwarded => setBlock(p => ({ ...p, blockForwarded }))} /></div></details>
      <details className="group mt-4 rounded-[14px] border border-white/[0.07] bg-white/[0.025]"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between px-3 text-[12px] font-semibold text-white">Вложения <ChevronDown size={15} className="text-[#66666E] transition-transform group-open:rotate-180" /></summary><div className="flex flex-wrap gap-2 border-t border-white/[0.07] p-3">{MEDIA.map(item => <button key={item.id} type="button" aria-pressed={block.blockedMedia.includes(item.id)} onClick={() => toggleMedia(item.id)} className={`min-h-11 cursor-pointer rounded-[10px] border px-3 text-[12px] transition-colors ${block.blockedMedia.includes(item.id) ? 'border-red-400/30 bg-red-400/10 text-red-300' : 'border-white/[0.08] bg-white/[0.035] text-[#8A8A93] hover:text-white'}`}>{item.label}</button>)}</div></details>
      <div className="mt-4 space-y-3 rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><label className="block text-[11px] text-[#8A8A93]">Реакция<select value={block.action} onChange={e => setBlock(p => ({ ...p, action: e.target.value as FiltersBlock['action'] }))} className={inputClass}><option value="delete">Удалить сообщение</option><option value="delete_warn">Удалить и предупредить</option></select></label><Switch label="Пропускать ботов" value={block.skipBots} onChange={skipBots => setBlock(p => ({ ...p, skipBots }))} /><Switch label="Пропускать админов" value={block.skipAdmins} onChange={skipAdmins => setBlock(p => ({ ...p, skipAdmins }))} /><Switch label="Пропускать доверенных" value={block.skipTrusted} onChange={skipTrusted => setBlock(p => ({ ...p, skipTrusted }))} /></div>
      {message && <p aria-live="polite" className="mt-3 text-[11px] text-[#8A8A93]">{message}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" size="sm" onClick={() => void save()} disabled={saving || publishing} fullWidth>{saving ? <Loader2 size={14} className="animate-spin" /> : <><Save size={14} /> Сохранить</>}</Button><Button variant="primary" size="sm" onClick={() => void publish()} disabled={saving || publishing} fullWidth>{publishing ? <Loader2 size={14} className="animate-spin" /> : 'Опубликовать'}</Button></div>
    </div>}
    <ModeratorHelpSheet kind="filters" open={helpOpen} onClose={() => setHelpOpen(false)} />
  </GlassCard>
}
