import { useCallback, useEffect, useState } from 'react'
import { Check, ChevronDown, Gavel, Loader2, Save } from 'lucide-react'
import { API_BASE } from '@/lib/api'
import { getTelegramInitData, moderatorFetch } from '@/lib/telegram'
import { GlassCard } from '@/components/ui/GlassCard'
import { Button } from '@/components/ui/Button'
import { Switch } from '@/components/ui/Switch'
import { ModeratorHelpSheet, ModeratorInfoButton } from './ModeratorHelpSheet'

type Policy = { id: string; type: 'warning_policy'; enabled: boolean; warningExpiryDays: number; muteAfterWarnings: number; muteDurationSeconds: number; banAfterWarnings: number; deleteCommandMessages: boolean; notifyUser: boolean; skipAdmins: boolean }
const DEFAULT: Policy = { id: 'warning-policy-default', type: 'warning_policy', enabled: true, warningExpiryDays: 30, muteAfterWarnings: 3, muteDurationSeconds: 3600, banAfterWarnings: 5, deleteCommandMessages: true, notifyUser: true, skipAdmins: true }
const selectClass = 'mt-1.5 min-h-11 w-full rounded-[11px] border border-white/[0.08] bg-[#171719] px-3 text-[13px] text-white outline-none focus:border-[rgba(255,106,0,0.45)]'

export function ModeratorWarningPolicyEditor({ moderatorId }: { moderatorId: string }) {
  const [block, setBlock] = useState(DEFAULT), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [publishing, setPublishing] = useState(false), [published, setPublished] = useState(false), [collapsed, setCollapsed] = useState(false), [helpOpen, setHelpOpen] = useState(false), [message, setMessage] = useState('')
  const initData = getTelegramInitData()
  useEffect(() => { if (!initData) { setLoading(false); return } moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft`).then(async r => { const d = await r.json() as { draft?: { blocks?: Policy[] }; moderator?: { publishedVersion?: number | null }; error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось загрузить правила'); const found = d.draft?.blocks?.find(x => x.type === 'warning_policy'); if (found) setBlock({ ...DEFAULT, ...found }); const yes = Boolean(d.moderator?.publishedVersion); setPublished(yes); if (yes) setCollapsed(true) }).catch(e => setMessage(e instanceof Error ? e.message : 'Не удалось загрузить правила')).finally(() => setLoading(false)) }, [initData, moderatorId])
  const save = useCallback(async () => { if (!initData) return false; setSaving(true); setMessage(''); try { const r = await moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/draft`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ blocks: [block] }) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось сохранить'); setMessage('Черновик сохранён'); return true } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось сохранить'); return false } finally { setSaving(false) } }, [block, initData, moderatorId])
  const publish = async () => { if (publishing) return; setPublishing(true); if (!await save()) { setPublishing(false); return } try { const r = await moderatorFetch(`${API_BASE}/api/moderator-config/${moderatorId}/publish`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) }); const d = await r.json() as { error?: string }; if (!r.ok) throw new Error(d.error ?? 'Не удалось опубликовать'); setPublished(true); setMessage('Правила опубликованы') } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось опубликовать') } finally { setPublishing(false) } }
  if (loading) return <div className="flex justify-center py-6 text-[#66666E]"><Loader2 size={20} className="animate-spin" /></div>
  return <GlassCard>
    <div className={`flex items-center gap-1 ${collapsed ? '' : 'mb-4'}`}><button type="button" aria-expanded={!collapsed} onClick={() => setCollapsed(v => !v)} className="flex min-h-14 min-w-0 flex-1 items-center gap-3 rounded-[14px] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[13px] bg-[rgba(255,106,0,0.10)] text-[#FF6A00]"><Gavel size={18} /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-[14px] font-semibold text-white">Правила и санкции {published && <span className="flex items-center gap-1 text-[10px] font-normal text-emerald-400"><Check size={11} /> опубликовано</span>}</span><span className="mt-0.5 block truncate text-[11px] text-[#66666E]">{collapsed ? `${block.muteAfterWarnings} warn → mute · ${block.banAfterWarnings} warn → ban` : 'Предупреждения, эскалация и команды'}</span></span><ChevronDown size={18} className={`shrink-0 text-[#66666E] transition-transform ${collapsed ? '-rotate-90' : ''}`} /></button><ModeratorInfoButton onClick={() => setHelpOpen(true)} label="Открыть справку: Правила и санкции" /></div>
    {!collapsed && <div><div className="rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Включить санкции" description="Считать предупреждения и повышать наказание" value={block.enabled} onChange={enabled => setBlock(p => ({ ...p, enabled }))} /></div>
      <div className="mt-4 grid grid-cols-2 gap-3"><label className="text-[11px] text-[#8A8A93]">Срок предупреждения<select value={block.warningExpiryDays} onChange={e => setBlock(p => ({ ...p, warningExpiryDays: Number(e.target.value) }))} className={selectClass}>{[0,1,7,14,30,60,90,180,365].map(v => <option key={v} value={v}>{v ? `${v} дн.` : 'Без срока'}</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Mute после<select value={block.muteAfterWarnings} onChange={e => setBlock(p => ({ ...p, muteAfterWarnings: Number(e.target.value) }))} className={selectClass}><option value={0}>Не применять</option>{[2,3,4,5,7,10].map(v => <option key={v} value={v}>{v} warn</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Длительность mute<select value={block.muteDurationSeconds} onChange={e => setBlock(p => ({ ...p, muteDurationSeconds: Number(e.target.value) }))} className={selectClass}>{[[600,'10 мин.'],[3600,'1 час'],[21600,'6 часов'],[86400,'1 день'],[604800,'7 дней'],[2592000,'30 дней']].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label className="text-[11px] text-[#8A8A93]">Ban после<select value={block.banAfterWarnings} onChange={e => setBlock(p => ({ ...p, banAfterWarnings: Number(e.target.value) }))} className={selectClass}><option value={0}>Не применять</option>{[3,4,5,7,10,15,20].map(v => <option key={v} value={v}>{v} warn</option>)}</select></label></div>
      <div className="mt-4 space-y-3 rounded-[14px] border border-white/[0.07] bg-white/[0.025] p-3"><Switch label="Удалять команды из чата" value={block.deleteCommandMessages} onChange={deleteCommandMessages => setBlock(p => ({ ...p, deleteCommandMessages }))} /><Switch label="Сообщать участнику результат" value={block.notifyUser} onChange={notifyUser => setBlock(p => ({ ...p, notifyUser }))} /><Switch label="Защищать администраторов" value={block.skipAdmins} onChange={skipAdmins => setBlock(p => ({ ...p, skipAdmins }))} /></div>
      <div className="mt-4 rounded-[14px] border border-white/[0.07] bg-[#0D0D0F] p-3"><p className="text-[11px] font-semibold uppercase tracking-wider text-[#66666E]">Команды ответом на сообщение</p><p className="mt-2 font-mono text-[11px] leading-6 text-[#A1A1AA]">/warn · /mute 1h · /unmute<br/>/ban · /kick · /unban · /delete · /info</p></div>
      {message && <p className="mt-3 text-[11px] text-[#8A8A93]">{message}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" size="sm" onClick={() => void save()} disabled={saving || publishing} fullWidth>{saving ? <Loader2 size={14} className="animate-spin" /> : <><Save size={14} /> Сохранить</>}</Button><Button variant="primary" size="sm" onClick={() => void publish()} disabled={saving || publishing} fullWidth>{publishing ? <Loader2 size={14} className="animate-spin" /> : 'Опубликовать'}</Button></div>
    </div>}
    <ModeratorHelpSheet kind="sanctions" open={helpOpen} onClose={() => setHelpOpen(false)} />
  </GlassCard>
}
