export type CommunityManagerConfigData = {
  identity: { displayName: string; role: string; bio: string; preset: string; tone: 'friendly'|'expert'|'energetic'|'neutral'; addressForm: 'ты'|'вы'; socialRoles: string[]; traits: string[]; speechStyles: string[]; humorStyles: string[]; profanityLevel: 'none'|'mild'|'natural'|'rough'; debateStyle: 'avoid'|'gentle'|'fact_check'|'devils_advocate'|'provoke'|'defuse'; expertiseStances: string[]; collectiveAddress: string; verbalHabits: string[]; customInstructions: string; humorLevel: number; initiativeLevel: number; forbiddenClaims: string[] };
  support: { useBrandKit: boolean; useProjectDocs: boolean; useFaq: boolean; answerProductQuestions: boolean; escalateWhenUnknown: boolean; escalationText: string; supportContactUrl: string };
  research: { mode: 'off'|'when_needed'|'deep'; showSources: boolean; sourcePolicy: 'allowlist'|'open'; allowedDomains: string[]; blockedDomains: string[]; maxSearchesPerAnswer: number; dailyLimit: number };
  replies: { replyToDirectReply: boolean; replyToMention: boolean; replyToProductQuestion: boolean; replyToUnansweredQuestion: boolean; ambientConversation: boolean; thematicConversation: boolean; moderatorFollowups: boolean; conversationMemory: boolean; participationLevel: 'quiet'|'selective'|'active'; ambientCooldownMinutes: number; unansweredAfterMinutes: number; maxThreadDepth: number; userCooldownSeconds: number };
  activities: { enabled: boolean; requireApproval: boolean; discussionEnabled: boolean; pollEnabled: boolean; gameEnabled: boolean; digestEnabled: boolean; silenceMinutes: number; silenceMinMinutes: number; silenceMaxMinutes: number; everyHours: number; maxInitiativesPerWeek: number; responseWindowMinutes: number; topics: string[] };
  limits: { timezone: string; quietEnabled: boolean; quietFrom: number; quietTo: number; maxRepliesPerHour: number; maxRepliesPerDay: number; maxInitiativesPerDay: number };
};

export const DEFAULT_CM_CONFIG: CommunityManagerConfigData = {
  identity: { displayName: 'Community Manager', role: 'Комьюнити-менеджер проекта', bio: 'Помогаю участникам, поддерживаю полезные обсуждения и знаю продукт.', preset: 'friendly_guide', tone: 'friendly', addressForm: 'ты', socialRoles: ['Свой человек','Помощник новичков'], traits: ['Тёплый','Любопытный'], speechStyles: ['Разговорная','Простыми словами'], humorStyles: ['Лёгкий'], profanityLevel: 'none', debateStyle: 'gentle', expertiseStances: ['Собеседник на равных','Честно признаёт незнание'], collectiveAddress: 'Ребята', verbalHabits: ['Короткие сообщения'], customInstructions: '', humorLevel: 1, initiativeLevel: 1, forbiddenClaims: ['не обещать сроки, цены и действия команды без источника'] },
  support: { useBrandKit: true, useProjectDocs: true, useFaq: true, answerProductQuestions: true, escalateWhenUnknown: true, escalationText: 'Я уточню это у команды проекта.', supportContactUrl: '' },
  research: { mode: 'when_needed', showSources: false, sourcePolicy: 'allowlist', allowedDomains: [], blockedDomains: ['youtube.com','youtu.be','tiktok.com','instagram.com','vk.com','dzen.ru'], maxSearchesPerAnswer: 3, dailyLimit: 20 },
  replies: { replyToDirectReply: true, replyToMention: true, replyToProductQuestion: true, replyToUnansweredQuestion: true, ambientConversation: true, thematicConversation: true, moderatorFollowups: true, conversationMemory: true, participationLevel: 'selective', ambientCooldownMinutes: 8, unansweredAfterMinutes: 15, maxThreadDepth: 4, userCooldownSeconds: 30 },
  activities: { enabled: true, requireApproval: false, discussionEnabled: true, pollEnabled: true, gameEnabled: true, digestEnabled: true, silenceMinutes: 60, silenceMinMinutes: 40, silenceMaxMinutes: 80, everyHours: 24, maxInitiativesPerWeek: 3, responseWindowMinutes: 120, topics: [] },
  limits: { timezone: 'Europe/Moscow', quietEnabled: true, quietFrom: 23, quietTo: 9, maxRepliesPerHour: 20, maxRepliesPerDay: 100, maxInitiativesPerDay: 1 },
};

const str=(v:unknown,f:string,max:number)=>typeof v==='string'&&v.trim()?v.trim().slice(0,max):f;
const num=(v:unknown,f:number,min:number,max:number)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):f));
const bool=(v:unknown,f:boolean)=>typeof v==='boolean'?v:f;
const list=(v:unknown,maxItems:number,maxLen:number)=>Array.isArray(v)?[...new Set(v.filter(x=>typeof x==='string').map(x=>String(x).trim().slice(0,maxLen)).filter(Boolean))].slice(0,maxItems):[];
const listOr=(v:unknown,f:string[],maxItems:number,maxLen:number)=>Array.isArray(v)?list(v,maxItems,maxLen):f;
const domains=(v:unknown,maxItems=30)=>list(v,maxItems,200).map(x=>{try{return new URL(x.includes('://')?x:'https://'+x).hostname.toLowerCase().replace(/^www\\./,'')}catch{return''}}).filter(x=>/^[a-z0-9.-]+$/.test(x)&&x.includes('.')).filter((x,i,a)=>a.indexOf(x)===i);

export function parseCommunityManagerConfig(raw: unknown): CommunityManagerConfigData {
  const r=(raw&&typeof raw==='object'?raw:{}) as Record<string,any>, d=DEFAULT_CM_CONFIG;
  const identity=r.identity??{},support=r.support??{},research=r.research??{},replies=r.replies??{},activities=r.activities??{},limits=r.limits??{};
  const tone=['friendly','expert','energetic','neutral'].includes(identity.tone)?identity.tone:d.identity.tone;
  const addressForm=['ты','вы'].includes(identity.addressForm)?identity.addressForm:d.identity.addressForm;
  const researchMode=['off','when_needed','deep'].includes(research.mode)?research.mode:d.research.mode;
  const sourcePolicy=['allowlist','open'].includes(research.sourcePolicy)?research.sourcePolicy:d.research.sourcePolicy;
  return {
    identity:{displayName:str(identity.displayName,d.identity.displayName,80),role:str(identity.role,d.identity.role,160),bio:str(identity.bio,d.identity.bio,2000),preset:str(identity.preset,d.identity.preset,80),tone,addressForm,socialRoles:listOr(identity.socialRoles,d.identity.socialRoles,4,80),traits:listOr(identity.traits,d.identity.traits,5,80),speechStyles:listOr(identity.speechStyles,d.identity.speechStyles,5,80),humorStyles:listOr(identity.humorStyles,d.identity.humorStyles,4,80),profanityLevel:['none','mild','natural','rough'].includes(identity.profanityLevel)?identity.profanityLevel:d.identity.profanityLevel,debateStyle:['avoid','gentle','fact_check','devils_advocate','provoke','defuse'].includes(identity.debateStyle)?identity.debateStyle:d.identity.debateStyle,expertiseStances:listOr(identity.expertiseStances,d.identity.expertiseStances,4,100),collectiveAddress:typeof identity.collectiveAddress==='string'?identity.collectiveAddress.trim().slice(0,80):d.identity.collectiveAddress,verbalHabits:listOr(identity.verbalHabits,d.identity.verbalHabits,6,100),customInstructions:typeof identity.customInstructions==='string'?identity.customInstructions.trim().slice(0,1200):'',humorLevel:num(identity.humorLevel,d.identity.humorLevel,0,3),initiativeLevel:num(identity.initiativeLevel,d.identity.initiativeLevel,0,3),forbiddenClaims:list(identity.forbiddenClaims,20,200)},
    support:{useBrandKit:bool(support.useBrandKit,d.support.useBrandKit),useProjectDocs:bool(support.useProjectDocs,d.support.useProjectDocs),useFaq:bool(support.useFaq,d.support.useFaq),answerProductQuestions:bool(support.answerProductQuestions,d.support.answerProductQuestions),escalateWhenUnknown:bool(support.escalateWhenUnknown,d.support.escalateWhenUnknown),escalationText:str(support.escalationText,d.support.escalationText,500),supportContactUrl:typeof support.supportContactUrl==='string'?support.supportContactUrl.trim().slice(0,500):''},
    research:{mode:researchMode,showSources:false,sourcePolicy,allowedDomains:domains(research.allowedDomains),blockedDomains:domains(research.blockedDomains).length?domains(research.blockedDomains):d.research.blockedDomains,maxSearchesPerAnswer:num(research.maxSearchesPerAnswer,d.research.maxSearchesPerAnswer,1,5),dailyLimit:num(research.dailyLimit,d.research.dailyLimit,0,200)},
    replies:{replyToDirectReply:bool(replies.replyToDirectReply,d.replies.replyToDirectReply),replyToMention:bool(replies.replyToMention,d.replies.replyToMention),replyToProductQuestion:bool(replies.replyToProductQuestion,d.replies.replyToProductQuestion),replyToUnansweredQuestion:bool(replies.replyToUnansweredQuestion,d.replies.replyToUnansweredQuestion),ambientConversation:bool(replies.ambientConversation,d.replies.ambientConversation),thematicConversation:bool(replies.thematicConversation,d.replies.thematicConversation),moderatorFollowups:bool(replies.moderatorFollowups,d.replies.moderatorFollowups),conversationMemory:bool(replies.conversationMemory,d.replies.conversationMemory),participationLevel:['quiet','selective','active'].includes(replies.participationLevel)?replies.participationLevel:d.replies.participationLevel,ambientCooldownMinutes:num(replies.ambientCooldownMinutes,d.replies.ambientCooldownMinutes,1,240),unansweredAfterMinutes:num(replies.unansweredAfterMinutes,d.replies.unansweredAfterMinutes,1,240),maxThreadDepth:num(replies.maxThreadDepth,d.replies.maxThreadDepth,1,10),userCooldownSeconds:num(replies.userCooldownSeconds,d.replies.userCooldownSeconds,0,3600)},
    activities:{enabled:bool(activities.enabled,d.activities.enabled),requireApproval:bool(activities.requireApproval,d.activities.requireApproval),discussionEnabled:bool(activities.discussionEnabled,d.activities.discussionEnabled),pollEnabled:bool(activities.pollEnabled,d.activities.pollEnabled),gameEnabled:bool(activities.gameEnabled,d.activities.gameEnabled),digestEnabled:bool(activities.digestEnabled,d.activities.digestEnabled),silenceMinutes:num(activities.silenceMinutes,d.activities.silenceMinutes,15,10080),silenceMinMinutes:num(activities.silenceMinMinutes,Math.max(15,num(activities.silenceMinutes,d.activities.silenceMinutes,15,10080)-20),15,10080),silenceMaxMinutes:num(activities.silenceMaxMinutes,num(activities.silenceMinutes,d.activities.silenceMinutes,15,10080)+20,15,10080),everyHours:num(activities.everyHours,d.activities.everyHours,1,168),maxInitiativesPerWeek:num(activities.maxInitiativesPerWeek,d.activities.maxInitiativesPerWeek,1,140),responseWindowMinutes:num(activities.responseWindowMinutes,d.activities.responseWindowMinutes,15,1440),topics:list(activities.topics,50,160)},
    limits:{timezone:str(limits.timezone,d.limits.timezone,80),quietEnabled:typeof limits.quietEnabled==='boolean'?limits.quietEnabled:num(limits.quietFrom,d.limits.quietFrom,0,23)!==num(limits.quietTo,d.limits.quietTo,0,23),quietFrom:num(limits.quietFrom,d.limits.quietFrom,0,23),quietTo:num(limits.quietTo,d.limits.quietTo,0,23),maxRepliesPerHour:num(limits.maxRepliesPerHour,d.limits.maxRepliesPerHour,1,100),maxRepliesPerDay:num(limits.maxRepliesPerDay,d.limits.maxRepliesPerDay,1,1000),maxInitiativesPerDay:num(limits.maxInitiativesPerDay,d.limits.maxInitiativesPerDay,0,20)},
  };
}

export function isQuietHour(config:CommunityManagerConfigData,date=new Date()):boolean{
  if(!config.limits.quietEnabled)return false;
  let hour=date.getUTCHours();
  try{hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:config.limits.timezone,hour:'2-digit',hourCycle:'h23'}).format(date));}catch{}
  const {quietFrom:a,quietTo:b}=config.limits;
  return a===b?false:a>b?(hour>=a||hour<b):(hour>=a&&hour<b);
}
export function randomInitiativeDate(config:CommunityManagerConfigData,from=new Date(),random=Math.random):Date{
  const min=Math.min(config.activities.silenceMinMinutes,config.activities.silenceMaxMinutes),max=Math.max(config.activities.silenceMinMinutes,config.activities.silenceMaxMinutes);
  const sample=Math.min(0.999999999,Math.max(0,random()));
  return new Date(from.getTime()+(min+Math.floor(sample*(max-min+1)))*60_000);
}
