import { useEffect, useRef, useState } from 'react'
import { Bot, Check, ChevronRight, ImagePlus, Loader2, Pencil, RefreshCw, Sparkles } from 'lucide-react'
import { Sheet } from '@/components/ui/Sheet'
import { Button } from '@/components/ui/Button'
import { API_BASE } from '@/lib/api'
import { getTelegramInitData, moderatorFetch } from '@/lib/telegram'
import { CommunityManagerHelpSheet, CommunityManagerInfoButton } from './CommunityManagerHelpSheet'
export type ManagedCommunityBotView={id:string;tgBotId:string|null;username:string|null;displayName:string;avatarUrl:string|null;status:string;lastError:string|null;requestExpiresAt:string|null}
type Props={communityId:string;sharedUsername:string;executorType:string;managedBot:ManagedCommunityBotView|null;suggestedBase:string;onRefresh:()=>Promise<void>}
const field='mt-1.5 min-h-12 w-full rounded-[12px] border border-white/[.08] bg-[#171719] px-3.5 text-[15px] text-white outline-none focus:border-[rgba(255,106,0,.45)] focus-visible:ring-2 focus-visible:ring-[#FF6A00]/30'
const suggest=(x:string)=>{let b=x.replace(/^@/,'').replace(/[^A-Za-z0-9_]/g,'').slice(0,22);if(!/^[A-Za-z]/.test(b))b='publium_'+b;return(b||'publium')+'_cm_bot'}
export function CommunityManagerExecutorSheet({communityId,sharedUsername,executorType,managedBot,suggestedBase,onRefresh}:Props){
 const initData=getTelegramInitData(),file=useRef<HTMLInputElement>(null),[open,setOpen]=useState(false),[create,setCreate]=useState(false),[edit,setEdit]=useState(false),[help,setHelp]=useState(false),[name,setName]=useState(managedBot?.displayName||'Community Manager '+suggestedBase.replace(/^@/,'')),[username,setUsername]=useState(suggest(suggestedBase)),[avatar,setAvatar]=useState<string|null>(managedBot?.avatarUrl||null),[url,setUrl]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('')
 useEffect(()=>{if(managedBot?.displayName)setName(managedBot.displayName);if(managedBot?.avatarUrl)setAvatar(managedBot.avatarUrl)},[managedBot?.displayName,managedBot?.avatarUrl])
 useEffect(()=>{if(!open||managedBot?.status!=='REQUESTED')return;const t=setInterval(()=>void onRefresh(),3000);return()=>clearInterval(t)},[open,managedBot?.status,onRefresh])
 const api=async(path:string,method:string,body?:Record<string,unknown>)=>{const r=await moderatorFetch(API_BASE+'/api/community-manager/communities/'+communityId+path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})}),d=await r.json()as{error?:string;createUrl?:string;warning?:string};if(!r.ok)throw Error(d.error||'Не удалось выполнить действие');return d}
 const run=async(key:string,fn:()=>Promise<void>)=>{setBusy(key);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить действие')}finally{setBusy('')}}
 const upload=(f:File)=>run('avatar',async()=>{if(!initData)throw Error('Откройте Publium внутри Telegram');const form=new FormData();form.append('initData',initData);form.append('image',f);const r=await moderatorFetch(API_BASE+'/api/posts/upload-block-image',{method:'POST',body:form}),d=await r.json()as{url?:string;error?:string};if(!r.ok||!d.url)throw Error(d.error||'Не удалось загрузить аватар');setAvatar(d.url)})
 const request=()=>run('request',async()=>{const d=await api('/managed-bot/request','POST',{displayName:name,username,avatarUrl:avatar});if(!d.createUrl)throw Error('Telegram не вернул ссылку');setUrl(d.createUrl);openLink(d.createUrl);await onRefresh()})
 const activate=()=>run('activate',async()=>{await api('/managed-bot/activate','POST');await onRefresh()})
 const shared=()=>run('shared',async()=>{if(executorType!=='SHARED'){await api('/executor/shared','POST');await onRefresh()}setOpen(false)})
 const save=()=>run('save',async()=>{const d=await api('/managed-bot/profile','PATCH',{displayName:name,avatarUrl:avatar});await onRefresh();setEdit(false);if(d.warning)setError(d.warning)})
 const custom=executorType==='CUSTOM'&&managedBot?.status==='ACTIVE',effectiveName=custom?managedBot?.displayName:'Community Manager Publium',effectiveUser=custom?managedBot?.username:sharedUsername
 return <><button type="button" onClick={()=>setOpen(true)} className="mt-3 flex min-h-16 w-full cursor-pointer items-center gap-3 rounded-[14px] border border-white/[.07] bg-white/[.035] px-3 py-2.5 text-left transition-colors hover:border-[rgba(255,106,0,.25)] hover:bg-white/[.055] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><Avatar url={custom?managedBot?.avatarUrl:null}/><span className="min-w-0 flex-1"><small className="block uppercase tracking-wider text-[#66666E]">Бот-исполнитель</small><b className="block truncate text-[13px] text-white">{effectiveName}</b><span className="block truncate text-[11px] text-[#777780]">@{effectiveUser}</span></span><i className="not-italic rounded-full border border-white/[.08] px-2 py-1 text-[9px] uppercase text-[#8A8A93]">{custom?'Свой':'Стандарт'}</i><ChevronRight size={16}/></button>
 <Sheet open={open} onClose={()=>setOpen(false)} title="Бот Community Manager" height="80"><div className="space-y-3"><div className="flex min-h-12 items-center gap-3 rounded-[13px] border border-white/[.07] bg-white/[.025] pl-3"><span className="min-w-0 flex-1 text-[11px] leading-relaxed text-[#8A8A93]">Выберите, от имени какого бота CM будет писать в чате.</span><CommunityManagerInfoButton onClick={()=>setHelp(true)} label="Как работает бот-исполнитель"/></div><CommunityManagerHelpSheet kind="executor" open={help} onClose={()=>setHelp(false)}/>
 <Choice active={executorType==='SHARED'} title="Стандартный бот" text={'@'+sharedUsername+' · готов к работе'} onClick={()=>void shared()}/>
 <div className={'rounded-[16px] border p-3.5 '+(custom?'border-[rgba(255,106,0,.35)] bg-[rgba(255,106,0,.07)]':'border-white/[.08] bg-white/[.025]')}><div className="flex gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-[13px] bg-[rgba(255,106,0,.12)] text-[#FF6A00]"><Sparkles size={19}/></span><span className="min-w-0 flex-1"><b className="text-[13px] text-white">Персональный Community Manager</b><span className="mt-1 block text-[11px] leading-relaxed text-[#777780]">Собственное имя, аватар и username для вашего сообщества.</span></span>{custom&&<Check size={17} className="text-[#FF6A00]"/>}</div>
 {!managedBot&&!create&&<Button className="mt-4" variant="primary" size="sm" fullWidth onClick={()=>setCreate(true)}>Настроить своего бота</Button>}
 {(create||managedBot?.status==='ERROR')&&!managedBot?.tgBotId&&<Step n={1} title="Оформление"><AvatarPicker refEl={file} url={avatar} busy={busy==='avatar'} upload={upload}/><label className="block text-[11px] text-[#8A8A93]">Название<input className={field} value={name} maxLength={64} onChange={e=>setName(e.target.value)}/></label><label className="block text-[11px] text-[#8A8A93]">Username<input className={field} value={username} maxLength={32} onChange={e=>setUsername(e.target.value.replace(/^@/,''))}/></label><p className="text-[10px] text-[#66666E]">5–32 символа, латиница, цифры и _. Окончание — bot.</p><Button variant="primary" size="sm" fullWidth disabled={!!busy} onClick={()=>void request()}>{busy==='request'?<Loader2 size={14} className="animate-spin"/>:'Создать в Telegram'}</Button></Step>}
 {managedBot?.status==='REQUESTED'&&<Step n={2} title="Подтверждение"><p className="rounded-[12px] bg-white/[.035] p-3 text-[11px] leading-relaxed text-[#A1A1AA]">Подтвердите создание в Telegram. Publium сам получит токен и настроит webhook.</p>{url&&<Button variant="secondary" size="sm" fullWidth onClick={()=>openLink(url)}>Открыть Telegram ещё раз</Button>}<button type="button" onClick={()=>void onRefresh()} className="flex min-h-11 w-full cursor-pointer items-center justify-center gap-2 text-[11px] text-[#8A8A93]"><RefreshCw size={13}/>Проверить создание</button></Step>}
 {managedBot?.tgBotId&&<Step n={3} title="Подключение"><div className="flex items-center gap-3 rounded-[13px] bg-white/[.035] p-3"><Avatar url={managedBot.avatarUrl}/><span className="min-w-0 flex-1"><b className="block truncate text-[13px] text-white">{managedBot.displayName}</b><small className="text-[#777780]">@{managedBot.username}</small></span><button type="button" onClick={()=>setEdit(!edit)} className="flex min-h-11 cursor-pointer items-center gap-1.5 rounded-[10px] border border-white/[.10] px-2.5 text-[11px] text-white"><Pencil size={13}/>{edit?'Скрыть':'Изменить'}</button></div>{edit&&<div className="space-y-3 rounded-[13px] border border-white/[.07] p-3"><AvatarPicker refEl={file} url={avatar} busy={busy==='avatar'} upload={upload}/><input aria-label="Название бота" className={field} value={name} onChange={e=>setName(e.target.value)}/><Button variant="primary" size="sm" fullWidth onClick={()=>void save()}>Сохранить</Button></div>}{!custom&&<><Button variant="secondary" size="sm" fullWidth onClick={()=>managedBot.username&&openLink('https://t.me/'+managedBot.username+'?startgroup=publium&admin=change_info')}>Добавить @{managedBot.username} администратором</Button><Button variant="primary" size="sm" fullWidth disabled={!!busy} onClick={()=>void activate()}>{busy==='activate'?<Loader2 size={14} className="animate-spin"/>:'Проверить и подключить'}</Button></>}{custom&&<p className="rounded-[12px] bg-emerald-400/[.07] p-3 text-[11px] text-emerald-300">Персональный бот активен и отвечает от имени вашего сообщества.</p>}</Step>}
 {managedBot?.lastError&&<p className="rounded-[11px] bg-amber-400/[.06] p-3 text-[10px] text-amber-300">{managedBot.lastError}</p>}</div>{error&&<p role="alert" className="rounded-[12px] bg-red-400/[.07] p-3 text-[11px] text-red-300">{error}</p>}</div></Sheet></>
}
const openLink=(url:string)=>window.open(url,'_blank','noopener,noreferrer')
function Choice({active,title,text,onClick}:{active:boolean;title:string;text:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={'flex min-h-[76px] w-full cursor-pointer items-center gap-3 rounded-[15px] border p-3 text-left transition-colors '+(active?'border-[rgba(255,106,0,.35)] bg-[rgba(255,106,0,.08)]':'border-white/[.08] bg-white/[.025]')}><span className="flex h-11 w-11 items-center justify-center rounded-[13px] bg-white/[.06] text-[#A1A1AA]"><Bot size={19}/></span><span className="min-w-0 flex-1"><b className="block text-[13px] text-white">{title}</b><small className="text-[#777780]">{text}</small></span>{active&&<Check size={17} className="text-[#FF6A00]"/>}</button>}
function Step({n,title,children}:{n:number;title:string;children:React.ReactNode}){return <div className="mt-4 space-y-3 border-t border-white/[.07] pt-4"><div className="flex gap-2">{[1,2,3].map(x=><i key={x} className={'h-1.5 flex-1 rounded-full '+(x<=n?'bg-[#FF6A00]':'bg-white/[.08]')}/>)}</div><p className="text-[11px] font-semibold uppercase tracking-wider text-[#777780]">Шаг {n} из 3 · {title}</p>{children}</div>}
function Avatar({url}:{url?:string|null}){return <span className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-[13px] bg-[rgba(255,106,0,.12)] text-[#FF6A00]">{url?<img src={url} alt="" className="h-full w-full object-cover"/>:<Bot size={19}/>}</span>}
function AvatarPicker({refEl,url,busy,upload}:{refEl:React.RefObject<HTMLInputElement|null>;url:string|null;busy:boolean;upload:(f:File)=>Promise<void>}){return <><input ref={refEl as React.RefObject<HTMLInputElement>} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=''}}/><button type="button" onClick={()=>refEl.current?.click()} className="flex min-h-16 w-full cursor-pointer items-center gap-3 rounded-[13px] border border-dashed border-white/[.12] px-3 text-left"><span className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-full bg-white/[.06] text-[#8A8A93]">{url?<img src={url} alt="Аватар бота" className="h-full w-full object-cover"/>:busy?<Loader2 size={17} className="animate-spin"/>:<ImagePlus size={18}/>}</span><span className="text-[12px] text-white">{url?'Заменить аватар':'Загрузить аватар'}</span></button></>}