import { useState } from 'react'
import { BadgeCheck, Trash2, UserRound } from 'lucide-react'
import { Switch } from '@/components/ui/Switch'

export type CommunityParticipant={id:string;tgUserId:string;username:string|null;displayName:string;relationship:string;roles:string[];expertise:string[];messageCount:number;cmExchangeCount:number;expertConfirmed:boolean;mentionEnabled:boolean;lastSeenAt:string}
const labels:Record<string,string>={NEW:'Новый',ACTIVE:'Активный',REGULAR:'Постоянный',FRIEND:'Знакомый',EXPERT:'Эксперт'}
export function CommunityManagerParticipants({items,onUpdate,onForget}:{items:CommunityParticipant[];onUpdate:(id:string,data:Record<string,unknown>)=>Promise<void>;onForget:(id:string)=>Promise<void>}){
 const [editing,setEditing]=useState<string|null>(null),[topics,setTopics]=useState('')
 if(!items.length)return <p className="text-[11px] leading-relaxed text-[#777780]">Карточки появятся после сообщений участников. CM хранит Telegram ID, публичное имя, счётчики общения и выбранные вами роли — без полного архива переписки.</p>
 return <div className="space-y-2">{items.map(item=><article key={item.id} className="rounded-[13px] border border-white/[0.07] bg-white/[0.025] p-3">
  <div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[12px] bg-[rgba(255,106,0,.10)] text-[#FF6A00]"><UserRound size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold text-white">{item.displayName}</p><p className="mt-0.5 truncate text-[10px] text-[#777780]">{item.username?'@'+item.username:'без username'} · {labels[item.relationship]??item.relationship}</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="rounded-full border border-white/[.07] px-2 py-1 text-[9px] text-[#A1A1AA]">{item.messageCount} сообщений</span><span className="rounded-full border border-white/[.07] px-2 py-1 text-[9px] text-[#A1A1AA]">{item.cmExchangeCount} диалогов с CM</span>{item.expertise.map(topic=><span key={topic} className="rounded-full border border-[rgba(255,106,0,.18)] bg-[rgba(255,106,0,.06)] px-2 py-1 text-[9px] text-[#FF9A57]">{topic}</span>)}</div></div><button type="button" aria-label="Забыть участника" onClick={()=>void onForget(item.id)} className="flex h-11 w-11 shrink-0 cursor-pointer items-center justify-center rounded-[10px] text-red-300 focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><Trash2 size={14}/></button></div>
  <div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>void onUpdate(item.id,{relationship:item.relationship==='FRIEND'?'REGULAR':'FRIEND'})} className={'min-h-11 cursor-pointer rounded-[10px] border px-2 text-[10px] font-semibold focus-visible:ring-2 focus-visible:ring-[#FF6A00] '+(item.relationship==='FRIEND'?'border-[rgba(255,106,0,.24)] bg-[rgba(255,106,0,.08)] text-[#FF9A57]':'border-white/[.07] text-[#A1A1AA]')}>Знакомый</button><button type="button" onClick={()=>void onUpdate(item.id,{expertConfirmed:!item.expertConfirmed})} className={'flex min-h-11 cursor-pointer items-center justify-center gap-1.5 rounded-[10px] border px-2 text-[10px] font-semibold focus-visible:ring-2 focus-visible:ring-[#FF6A00] '+(item.expertConfirmed?'border-emerald-400/20 bg-emerald-400/[.07] text-emerald-300':'border-white/[.07] text-[#A1A1AA]')}><BadgeCheck size={13}/> Эксперт</button></div>
  {item.expertConfirmed&&<div className="mt-3"><Switch label="Можно иногда упоминать" description={item.username?'Не чаще раза в сутки и только по совпавшей теме':'Нужен публичный username Telegram'} value={item.mentionEnabled&&Boolean(item.username)} onChange={mentionEnabled=>void onUpdate(item.id,{mentionEnabled})}/><button type="button" onClick={()=>{setEditing(editing===item.id?null:item.id);setTopics(item.expertise.join(', '))}} className="mt-2 min-h-11 cursor-pointer text-[10px] font-semibold text-[#FF8A3D] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]">Темы экспертизы</button>{editing===item.id&&<div className="flex gap-2"><input aria-label="Темы экспертизы" value={topics} onChange={event=>setTopics(event.target.value)} className="min-h-11 min-w-0 flex-1 rounded-[10px] border border-white/[.08] bg-[#0B0B0D] px-3 text-[11px] text-white outline-none focus:border-[rgba(255,106,0,.45)]" placeholder="биткоин, DeFi, prediction markets"/><button type="button" onClick={()=>{void onUpdate(item.id,{expertise:topics.split(/[,;\n]/).map(x=>x.trim()).filter(Boolean)});setEditing(null)}} className="min-h-11 cursor-pointer rounded-[10px] bg-[rgba(255,106,0,.12)] px-3 text-[10px] font-semibold text-[#FF8A3D]">Готово</button></div>}</div>}
 </article>)}</div>
}
