import { createPortal } from 'react-dom'
import { CircleHelp, Lightbulb, Settings2 } from 'lucide-react'
import { Sheet } from '@/components/ui/Sheet'

export type CommunityManagerHelpKind='overview'|'executor'|'identity'|'knowledge'|'research'|'replies'|'activities'|'simulator'|'log'
type Section={title:string;text?:string;items?:string[]}
const HELP:Record<CommunityManagerHelpKind,{title:string;intro:string;sections:Section[]}>= {
 overview:{title:'Что умеет Community Manager',intro:'Community Manager общается в привязанной Telegram-группе от имени выбранного бота и помогает владельцу поддерживать живое, полезное сообщество.',sections:[{title:'Что он делает',items:['Отвечает на упоминания, reply и вопросы по теме проекта.','Использует стиль канала, документы проекта и подтверждённые FAQ.','При необходимости ищет актуальные сведения в интернете и показывает источники.','Запускает обсуждения, опросы и дайджесты, сохраняя историю решений в журнале.']},{title:'Как он ведёт диалог',text:'Несколько быстрых сообщений одного участника объединяются в один смысловой запрос. CM отвечает один раз, не перебивает каждую реплику и соблюдает cooldown и общие лимиты.'},{title:'Запуск',items:['Выберите стандартного или персонального бота.','Заполните личность и знания, затем нажмите «Применить».','Кнопка «Запустить» включает автоматическую работу, «Пауза» полностью останавливает ответы.']}]},
 executor:{title:'Бот-исполнитель CM',intro:'Это Telegram-аккаунт бота, от имени которого Community Manager пишет в группе.',sections:[{title:'Стандартный бот',text:'@Publium_CM_Bot уже настроен и подходит для быстрого запуска.'},{title:'Персональный бот',text:'Создаётся через Telegram прямо из Publium. У него собственные имя, аватар и username; токен шифруется и не показывается в интерфейсе.'},{title:'Подключение',items:['Задайте имя, username с окончанием bot и при желании аватар.','Подтвердите создание в Telegram.','Добавьте бота администратором группы и нажмите «Проверить и подключить».']}]},
 identity:{title:'Личность CM',intro:'Определяет, кем представляется Community Manager и как звучат его ответы.',sections:[{title:'Имя и роль',text:'Используются в системном контексте и помогают сохранять устойчивый характер общения.'},{title:'Биография и тон',text:'Опишите компетенции, манеру речи и границы. Не помещайте сюда секреты или непроверенные обещания.'},{title:'Запреты',text:'Каждая строка — отдельное утверждение, которое CM не должен делать от имени проекта.'}]},
 knowledge:{title:'Знания и поддержка',intro:'Здесь задаются доверенные сведения, на которые CM опирается при ответах о проекте.',sections:[{title:'Источники знаний',items:['Стиль канала задаёт тему, аудиторию и голос.','Документы проекта содержат подробную базу знаний.','FAQ хранит короткие подтверждённые ответы с высоким приоритетом.']},{title:'Если ответа нет',text:'CM не должен придумывать факт: он использует текст эскалации и предлагает уточнить вопрос у команды.'}]},
 research:{title:'Интернет-ресерч',intro:'Ресерч нужен только для вопросов, где данные могли измениться: новости, цены, релизы и текущие события.',sections:[{title:'При необходимости',text:'Обычные объяснения берутся из знаний без поиска. Актуальный вопрос запускает поиск автоматически.'},{title:'Глубокий режим',text:'Использует более тщательный разбор, но отвечает медленнее и расходует больше лимита.'},{title:'Источники',text:'Если переключатель включён, в конце ответа будут прямые ссылки на использованные материалы.'}]},
 replies:{title:'Ответы и лимиты',intro:'Настройки определяют, когда CM вступает в разговор и как часто может писать.',sections:[{title:'Надёжные триггеры',text:'Reply и прямое упоминание считаются явным обращением и получают ответ.'},{title:'Обычная беседа',text:'Включайте осторожно: CM будет сам выбирать тематические реплики. Серия сообщений одного человека всё равно объединяется в один ответ.'},{title:'Ограничения',text:'Cooldown считается от последнего отправленного ответа. Часовые, суточные лимиты и тихие часы защищают чат от спама.'}]},
 activities:{title:'Активности',intro:'CM может подготовить отдельную тему, Telegram-опрос или краткий дайджест.',sections:[{title:'Тема',text:'Если поле пустое, CM берёт тему из настроенного списка интересов сообщества.'},{title:'Когда отправляется',text:'Кнопка запускает активность сразу. Во время паузы активности недоступны.'}]},
 simulator:{title:'Симулятор',intro:'Показывает решение CM без отправки сообщения в Telegram.',sections:[{title:'Что проверять',items:['Ответит CM или промолчит.','Какой intent распознан и насколько уверенно.','Какие FAQ или фрагменты документов найдены.']},{title:'Важно',text:'Симулятор проверяет маршрутизацию и знания; итоговая формулировка ответа в чате может отличаться.'}]},
 log:{title:'Журнал CM',intro:'Журнал объясняет, почему Community Manager ответил, промолчал или столкнулся с ошибкой.',sections:[{title:'Основные решения',items:['RESPOND — сообщение отправлено.','SILENT — CM осознанно промолчал из-за контекста, cooldown или модерации.','ACTIVITY — отправлена тема, опрос или дайджест.']},{title:'Склейка сообщений',text:'Запись burst_superseded означает, что реплика вошла в следующий, объединённый ответ и отдельно не обрабатывалась.'}]},
}
export function CommunityManagerInfoButton({onClick,label}:{onClick:()=>void;label:string}){return <button type="button" onClick={e=>{e.stopPropagation();onClick()}} aria-label={label} title={label} className="flex h-11 w-11 shrink-0 cursor-pointer items-center justify-center rounded-[12px] text-[#777780] transition-colors hover:bg-white/[.06] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><CircleHelp size={18}/></button>}
export function CommunityManagerHelpSheet({kind,open,onClose}:{kind:CommunityManagerHelpKind;open:boolean;onClose:()=>void}){const h=HELP[kind];if(typeof document==='undefined')return null;return createPortal(<Sheet open={open} onClose={onClose} title={h.title} height="80"><div className="space-y-3 pb-[max(12px,env(safe-area-inset-bottom))]"><div className="flex gap-3 rounded-[16px] border border-[rgba(255,106,0,.18)] bg-[rgba(255,106,0,.08)] p-3.5"><CircleHelp size={18} className="mt-0.5 shrink-0 text-[#FF6A00]"/><p className="text-[13px] leading-relaxed text-[#D4D4D8]">{h.intro}</p></div>{h.sections.map((x,i)=><section key={x.title} className="rounded-[16px] border border-white/[.07] bg-white/[.025] p-4"><div className="flex items-center gap-2">{i===h.sections.length-1?<Lightbulb size={15} className="text-[#FF6A00]"/>:<Settings2 size={15} className="text-[#777780]"/>}<h3 className="text-[13px] font-semibold text-white">{x.title}</h3></div>{x.text&&<p className="mt-2 text-[12px] leading-relaxed text-[#A1A1AA]">{x.text}</p>}{x.items&&<ul className="mt-2 space-y-2">{x.items.map(v=><li key={v} className="flex gap-2 text-[12px] leading-relaxed text-[#A1A1AA]"><span className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-[#FF6A00]"/>{v}</li>)}</ul>}</section>)}</div></Sheet>,document.body)}