import { AlertTriangle, Check, Newspaper, Trophy } from 'lucide-react'
import { Switch } from '@/components/ui/Switch'

export type ActivitySettings={enabled:boolean;requireApproval:boolean;intensity:'quiet'|'balanced'|'active';discussionEnabled:boolean;pollEnabled:boolean;quizEnabled:boolean;lightEnabled:boolean;hotNewsEnabled:boolean;digestEnabled:boolean;predictionEnabled:boolean;challengeEnabled:boolean;contestEnabled:boolean;contentSupportEnabled:boolean;rewardMode:'none'|'virtual'|'manual';rewardDescription:string;maxInitiativesPerWeek:number;responseWindowMinutes:number;topics:string[]}

const input='mt-1.5 min-h-11 w-full rounded-[11px] border border-white/[0.08] bg-[#0B0B0D] px-3 text-[13px] text-white outline-none focus:border-[rgba(255,106,0,0.5)] focus-visible:ring-2 focus-visible:ring-[#FF6A00]/30'
const area=input+' resize-none py-3 leading-relaxed'
const label='block text-[11px] font-medium text-[#9A9AA2]'
const manualTypes=[['DISCUSSION','Обсуждение'],['POLL','Опрос'],['QUIZ','Викторина'],['LIGHT','Лёгкая'],['HOT_NEWS','Горячая новость'],['DIGEST','Дайджест'],['PREDICTION','Прогноз'],['CHALLENGE','Челлендж'],['CONTEST','Конкурс']] as const

export function CommunityManagerActivities({value,onChange,managerEnabled,busy,topic,onTopicChange,onRun}:{value:ActivitySettings;onChange:(next:ActivitySettings)=>void;managerEnabled:boolean;busy:boolean;topic:string;onTopicChange:(value:string)=>void;onRun:(type:string)=>void}){
 const set=<K extends keyof ActivitySettings>(key:K,next:ActivitySettings[K])=>onChange({...value,[key]:next})
 const automatic=value.enabled&&!value.requireApproval
 const typeEnabled=(type:typeof manualTypes[number][0])=>({DISCUSSION:value.discussionEnabled,POLL:value.pollEnabled,QUIZ:value.quizEnabled,LIGHT:value.lightEnabled,HOT_NEWS:value.hotNewsEnabled,DIGEST:value.digestEnabled,PREDICTION:value.predictionEnabled,CHALLENGE:value.challengeEnabled,CONTEST:value.contestEnabled})[type]
 return <div className="space-y-4">
  <Switch label="Движок активностей" description="CM сам оценивает состояние чата и выбирает уместное действие — либо ничего не делает" value={automatic} onChange={enabled=>onChange({...value,enabled,requireApproval:!enabled})}/>
  {automatic&&<>
   <div><p className={label}>Интенсивность</p><div className="mt-2 grid grid-cols-3 gap-2" role="group" aria-label="Интенсивность активностей">{([['quiet','Спокойная'],['balanced','Баланс'],['active','Активная']] as const).map(([id,text])=><button key={id} type="button" aria-pressed={value.intensity===id} onClick={()=>set('intensity',id)} className={'min-h-11 cursor-pointer rounded-[11px] border px-2 text-[11px] font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00] '+(value.intensity===id?'border-[#FF6A00]/45 bg-[#FF6A00]/12 text-[#FF8A3D]':'border-white/[.08] text-[#8A8A93] hover:bg-white/[.04]')}>{value.intensity===id&&<Check size={12} className="mr-1 inline"/>}{text}</button>)}</div><p className="mt-2 text-[10px] leading-relaxed text-[#66666E]">Время выбирается случайно. CM учитывает живой разговор, недавние форматы и реакцию аудитории — настраивать каждый таймер не нужно.</p></div>
   <div className="space-y-2"><p className={label}>Разговор и вовлечение</p><Switch label="Обсуждения и вопросы" value={value.discussionEnabled} onChange={v=>set('discussionEnabled',v)}/><Switch label="Опросы" value={value.pollEnabled} onChange={v=>set('pollEnabled',v)}/><Switch label="Викторины" value={value.quizEnabled} onChange={v=>set('quizEnabled',v)}/><Switch label="Лёгкие активности" description="Факты, ассоциации, уместные шутки и короткие игровые вопросы" value={value.lightEnabled} onChange={v=>set('lightEnabled',v)}/><Switch label="Прогнозы" description="Только проверяемый исход и срок, без обещаний доходности" value={value.predictionEnabled} onChange={v=>set('predictionEnabled',v)}/></div>
   <div className="space-y-2"><p className={label}>Информация и контент</p><Switch label="Горячие новости" description="Только через настроенный интернет-ресерч и без публикации источников" value={value.hotNewsEnabled} onChange={v=>set('hotNewsEnabled',v)}/><Switch label="Дайджесты чата" description="Только когда накопилось содержательное обсуждение" value={value.digestEnabled} onChange={v=>set('digestEnabled',v)}/><Switch label="Сопровождать посты канала" description="Иногда подогревать отложенный пост, поддерживать релиз и обсуждение после него" value={value.contentSupportEnabled} onChange={v=>set('contentSupportEnabled',v)}/></div>
   <div className="rounded-[13px] border border-white/[.07] p-3"><div className="flex items-start gap-3"><Trophy size={18} className="mt-0.5 shrink-0 text-[#FF6A00]"/><div><p className="text-[11px] font-semibold text-white">Конкурсы и челленджи</p><p className="mt-1 text-[10px] leading-relaxed text-[#777780]">Никогда не запускаются автоматически. Владелец лично нажимает запуск и отвечает за выдачу награды.</p></div></div><div className="mt-3 space-y-2"><Switch label="Разрешить челленджи" value={value.challengeEnabled} onChange={v=>set('challengeEnabled',v)}/><Switch label="Разрешить конкурсы" value={value.contestEnabled} onChange={v=>set('contestEnabled',v)}/>{(value.challengeEnabled||value.contestEnabled)&&<><label className={label}>Награда<select value={value.rewardMode} onChange={e=>set('rewardMode',e.target.value as ActivitySettings['rewardMode'])} className={input}><option value="none">Без награды</option><option value="virtual">Виртуальная роль или доступ</option><option value="manual">Владелец выдаёт вручную</option></select></label>{value.rewardMode!=='none'&&<label className={label}>Что получает победитель<textarea rows={2} value={value.rewardDescription} onChange={e=>set('rewardDescription',e.target.value)} className={area} placeholder="Например: месяц подписки Creator"/></label>}<p className="flex gap-2 text-[10px] leading-relaxed text-amber-200/80"><AlertTriangle size={14} className="shrink-0"/>CM не подключает кошелёк, не обещает автоматическую выплату и не меняет условия после запуска.</p></>}</div></div>
   <label htmlFor="cm-activity-topics" className={label}>Приоритетные темы<textarea id="cm-activity-topics" rows={4} value={value.topics.join('\n')} onChange={e=>set('topics',e.target.value.split('\n').map(x=>x.trim()))} className={area} placeholder={'Трейдинг без лишнего риска\nPrediction markets\nРазбор криптоновостей'}/></label>
  </>}
  <div className="border-t border-white/[.06] pt-4"><div className="flex items-center gap-2"><Newspaper size={15} className="text-[#FF6A00]"/><p className="text-[11px] font-semibold text-white">Запустить вручную</p></div><label htmlFor="cm-activity-topic" className={label+' mt-3'}>Тема, правила или условия<input id="cm-activity-topic" value={topic} onChange={e=>onTopicChange(e.target.value)} className={input} placeholder="Пусто — CM выберет тему сам"/></label><div className="mt-3 grid grid-cols-2 gap-2">{manualTypes.filter(([type])=>typeEnabled(type)).map(([type,text])=><button type="button" key={type} onClick={()=>onRun(type)} disabled={busy||!managerEnabled} className="min-h-11 cursor-pointer rounded-[11px] border border-white/[.08] px-2 text-[10px] font-semibold text-white transition-colors hover:bg-white/[.04] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00] disabled:cursor-not-allowed disabled:opacity-40">{text}</button>)}</div></div>
 </div>
}
