import { useCallback, useEffect, useState } from 'react'
import { Activity, Bot, BookOpen, Check, ChevronDown, FlaskConical, Globe2, Loader2, MessageCircle, Pause, Play, Plus, Save, Send, Sparkles, Trash2 } from 'lucide-react'
import { API_BASE } from '@/lib/api'
import { getTelegramInitData, moderatorFetch } from '@/lib/telegram'
import { GlassCard } from '@/components/ui/GlassCard'
import { Button } from '@/components/ui/Button'
import { Switch } from '@/components/ui/Switch'
import { CommunityManagerHelpSheet, CommunityManagerInfoButton, type CommunityManagerHelpKind } from './CommunityManagerHelpSheet'
import { CommunityManagerExecutorSheet, type ManagedCommunityBotView } from './CommunityManagerExecutorSheet'

type Config={
 identity:{displayName:string;role:string;bio:string;tone:string;addressForm:string;humorLevel:number;initiativeLevel:number;forbiddenClaims:string[]}
 support:{useBrandKit:boolean;useProjectDocs:boolean;useFaq:boolean;answerProductQuestions:boolean;escalateWhenUnknown:boolean;escalationText:string;supportContactUrl:string}
 research:{mode:string;showSources:boolean;maxSearchesPerAnswer:number;dailyLimit:number}
 replies:{replyToDirectReply:boolean;replyToMention:boolean;replyToProductQuestion:boolean;replyToUnansweredQuestion:boolean;ambientConversation:boolean;unansweredAfterMinutes:number;maxThreadDepth:number;userCooldownSeconds:number}
 activities:{enabled:boolean;requireApproval:boolean;discussionEnabled:boolean;pollEnabled:boolean;digestEnabled:boolean;everyHours:number;topics:string[]}
 limits:{timezone:string;quietFrom:number;quietTo:number;maxRepliesPerHour:number;maxRepliesPerDay:number;maxInitiativesPerDay:number}
}
type Manager={id:string;status:string;enabled:boolean;mode:string;executorType:string;publishedVersion:number|null;lastActionAt:string|null;lastError:string|null}
type ActionRow={id:string;decision:string;intent:string|null;reason:string|null;response:string|null;status:string;createdAt:string}
type State={communityId:string|null;chat:{title:string;tgChatId:string}|null;manager:Manager|null;botUsername:string;sharedBotUsername:string;managedBot:ManagedCommunityBotView|null;docsCount:number;faqCount:number;actions:ActionRow[]}
const input='mt-1.5 min-h-11 w-full rounded-[11px] border border-white/[0.08] bg-[#0B0B0D] px-3 text-[13px] text-white outline-none focus:border-[rgba(255,106,0,0.5)] focus-visible:ring-2 focus-visible:ring-[#FF6A00]/30'
const area=input+' resize-none py-3 leading-relaxed'
const label='block text-[11px] font-medium text-[#9A9AA2]'
const initial:Config={identity:{displayName:'Community Manager',role:'Комьюнити-менеджер проекта',bio:'Помогаю участникам и знаю продукт.',tone:'friendly',addressForm:'ты',humorLevel:1,initiativeLevel:1,forbiddenClaims:[]},support:{useBrandKit:true,useProjectDocs:true,useFaq:true,answerProductQuestions:true,escalateWhenUnknown:true,escalationText:'Я уточню это у команды проекта.',supportContactUrl:''},research:{mode:'when_needed',showSources:true,maxSearchesPerAnswer:3,dailyLimit:20},replies:{replyToDirectReply:true,replyToMention:true,replyToProductQuestion:true,replyToUnansweredQuestion:false,ambientConversation:false,unansweredAfterMinutes:15,maxThreadDepth:4,userCooldownSeconds:30},activities:{enabled:false,requireApproval:true,discussionEnabled:true,pollEnabled:true,digestEnabled:true,everyHours:24,topics:[]},limits:{timezone:'Europe/Moscow',quietFrom:23,quietTo:9,maxRepliesPerHour:20,maxRepliesPerDay:100,maxInitiativesPerDay:2}}

function Section({icon,title,summary,help,children}:{icon:React.ReactNode;title:string;summary:string;help:CommunityManagerHelpKind;children:React.ReactNode}){
 const [open,setOpen]=useState(false),[helpOpen,setHelpOpen]=useState(false)
 return <GlassCard><div className="flex min-h-14 w-full items-center gap-1"><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="flex min-h-14 min-w-0 flex-1 cursor-pointer items-center gap-3 rounded-[12px] text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[13px] bg-[rgba(255,106,0,0.10)] text-[#FF6A00]">{icon}</span><span className="min-w-0 flex-1"><span className="block text-[14px] font-semibold text-white">{title}</span><span className="mt-0.5 block truncate text-[11px] text-[#777780]">{summary}</span></span></button><CommunityManagerInfoButton onClick={()=>setHelpOpen(true)} label={'Справка: '+title}/><button type="button" aria-label={open?'Свернуть':'Открыть'} onClick={()=>setOpen(v=>!v)} className="flex h-11 w-8 shrink-0 cursor-pointer items-center justify-center rounded-[10px] focus-visible:ring-2 focus-visible:ring-[#FF6A00]"><ChevronDown size={17} className={'text-[#66666E] transition-transform '+(open?'rotate-180':'')} /></button></div>{open&&<div className="mt-4 border-t border-white/[0.06] pt-4">{children}</div>}<CommunityManagerHelpSheet kind={help} open={helpOpen} onClose={()=>setHelpOpen(false)}/></GlassCard>
}

function OverviewHelp(){
 const [open,setOpen]=useState(false)
 return <><CommunityManagerInfoButton onClick={()=>setOpen(true)} label="Что умеет Community Manager"/><CommunityManagerHelpSheet kind="overview" open={open} onClose={()=>setOpen(false)}/></>
}
export function CommunityManagerPanel({channelId,channelUsername}:{channelId:string;channelUsername:string}){
 const [state,setState]=useState<State|null>(null),[config,setConfig]=useState<Config>(initial),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[actions,setActions]=useState<ActionRow[]>([]),[faqs,setFaqs]=useState<Array<{id:string;question:string;answer:string}>>([]),[faqQ,setFaqQ]=useState(''),[faqA,setFaqA]=useState(''),[simText,setSimText]=useState(''),[simulation,setSimulation]=useState<any>(null),[activityTopic,setActivityTopic]=useState('')
 const initData=getTelegramInitData()
 const api=useCallback(async(path:string,options?:RequestInit)=>{const r=await moderatorFetch(API_BASE+'/api/community-manager'+path,options),d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка Community Manager');return d},[])
 const load=useCallback(async()=>{if(!initData)return;try{const d=await api('/channels/'+channelId);setState(d);setActions(d.actions||[]);if(d.manager){const draft=await api('/'+d.manager.id+'/draft');setConfig(draft.config);const f=await api('/'+d.manager.id+'/faq');setFaqs(f.faqs||[])}}catch(e){setMessage(e instanceof Error?e.message:'Не удалось загрузить')}finally{setLoading(false)}},[api,channelId,initData])
 useEffect(()=>{void load()},[load])
 const act=async(key:string,fn:()=>Promise<void>)=>{setBusy(key);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'Ошибка')}finally{setBusy('')}}
 const create=()=>act('create',async()=>{await api('/channels/'+channelId+'/create',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await load()})
 const save=async(apply=false)=>{if(!state?.manager)return;await act(apply?'apply':'save',async()=>{await api('/'+state.manager!.id+'/draft',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({config,mode:'AUTOPILOT'})});if(apply){await api('/'+state.manager!.id+'/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});setMessage('Настройки применены, CM запущен')}else setMessage('Черновик сохранён');await load()})}
 const pause=()=>state?.manager&&act('pause',async()=>{await api('/'+state.manager!.id+'/pause',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!state.manager!.enabled,mode:'AUTOPILOT'})});await load()})
 const simulate=()=>state?.manager&&act('simulate',async()=>setSimulation(await api('/'+state.manager!.id+'/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:simText,config})})))
 const addFaq=()=>state?.manager&&act('faq',async()=>{await api('/'+state.manager!.id+'/faq',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:faqQ,answer:faqA})});setFaqQ('');setFaqA('');await load()})
 const delFaq=(id:string)=>state?.manager&&act('faq',async()=>{await api('/'+state.manager!.id+'/faq/'+id,{method:'DELETE'});await load()})
 const runActivity=(type:string)=>state?.manager&&act('activity',async()=>{await api('/'+state.manager!.id+'/activities/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,topic:activityTopic})});setMessage('Активность отправлена в чат');await load()})
 const sendDraft=(id:string)=>state?.manager&&act('draft',async()=>{await api('/'+state.manager!.id+'/actions/'+id+'/send',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await load()})
 if(loading)return <div className="flex justify-center py-20 text-[#66666E]"><Loader2 size={22} className="animate-spin"/></div>
 if(!state?.communityId)return <GlassCard strong><div className="text-center"><Sparkles size={26} className="mx-auto text-[#FF6A00]"/><p className="mt-3 text-[14px] font-semibold text-white">Сначала подключите группу</p><p className="mt-1 text-[12px] leading-relaxed text-[#777780]">Community Manager работает в группе, связанной с каналом через Moderator.</p></div></GlassCard>
 if(!state.manager)return <GlassCard strong><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-[14px] bg-[rgba(255,106,0,0.1)] text-[#FF6A00]"><Sparkles size={20}/></span><div><h2 className="text-[15px] font-semibold text-white">Community Manager</h2><p className="mt-1 text-[12px] leading-relaxed text-[#777780]">Создайте профиль CM и подключите отдельного бота.</p></div></div><Button variant="primary" size="sm" fullWidth disabled={busy==='create'} onClick={create}>{busy==='create'?<Loader2 size={14} className="animate-spin"/>:<><Plus size={14}/> Создать Community Manager</>}</Button></GlassCard>
 const m=state.manager
 return <div className="space-y-3" role="tabpanel" aria-label="Community Manager">
  <GlassCard strong className="relative overflow-hidden"><div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-[rgba(255,106,0,0.09)] blur-3xl"/><div className="relative"><div className="flex items-start gap-2"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-[14px] border border-[rgba(255,106,0,0.2)] bg-[rgba(255,106,0,0.1)] text-[#FF6A00]"><Bot size={20}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-[15px] font-semibold text-white">Community Manager</h2><span className={'rounded-full px-2 py-0.5 text-[10px] font-semibold '+(m.enabled?'bg-emerald-400/10 text-emerald-300':'bg-amber-400/10 text-amber-300')}>{m.enabled?'Активен':'Пауза'}</span></div><p className="mt-1 truncate text-[12px] text-[#777780]">{state.chat?.title}</p></div><OverviewHelp/></div><CommunityManagerExecutorSheet communityId={state.communityId} sharedUsername={state.sharedBotUsername} executorType={m.executorType} managedBot={state.managedBot} suggestedBase={channelUsername} onRefresh={load}/><Button className="mt-3" variant={m.enabled?'secondary':'primary'} size="sm" fullWidth onClick={pause} disabled={busy==='pause'}>{busy==='pause'?<Loader2 size={14} className="animate-spin"/>:m.enabled?<><Pause size={14}/> Поставить на паузу</>:<><Play size={14}/> Запустить Community Manager</>}</Button>{m.lastError&&<p role="alert" className="mt-3 rounded-[10px] bg-red-400/[.08] px-3 py-2 text-[11px] text-red-300">{m.lastError}</p>}</div></GlassCard>

  <Section help="identity" icon={<Sparkles size={18}/>} title="Личность CM" summary={config.identity.displayName+' · '+config.identity.role}><div className="space-y-4"><label className={label}>Имя<input value={config.identity.displayName} onChange={e=>setConfig({...config,identity:{...config.identity,displayName:e.target.value}})} className={input}/></label><label className={label}>Роль<input value={config.identity.role} onChange={e=>setConfig({...config,identity:{...config.identity,role:e.target.value}})} className={input}/></label><label className={label}>Биография<textarea rows={4} value={config.identity.bio} onChange={e=>setConfig({...config,identity:{...config.identity,bio:e.target.value}})} className={area}/></label><div className="grid grid-cols-2 gap-3"><label className={label}>Тон<select value={config.identity.tone} onChange={e=>setConfig({...config,identity:{...config.identity,tone:e.target.value}})} className={input}><option value="friendly">Дружелюбный</option><option value="expert">Экспертный</option><option value="energetic">Энергичный</option><option value="neutral">Нейтральный</option></select></label><label className={label}>Обращение<select value={config.identity.addressForm} onChange={e=>setConfig({...config,identity:{...config.identity,addressForm:e.target.value}})} className={input}><option value="ты">На ты</option><option value="вы">На вы</option></select></label></div><label className={label}>Запрещённые обещания<textarea rows={3} value={config.identity.forbiddenClaims.join('\n')} onChange={e=>setConfig({...config,identity:{...config.identity,forbiddenClaims:e.target.value.split('\n').filter(Boolean)}})} className={area}/></label></div></Section>

  <Section help="knowledge" icon={<BookOpen size={18}/>} title="Знания и поддержка" summary={state.docsCount+' документов · '+faqs.length+' FAQ'}><div className="space-y-3"><Switch label="Использовать стиль канала" value={config.support.useBrandKit} onChange={v=>setConfig({...config,support:{...config.support,useBrandKit:v}})}/><Switch label="Использовать документы проекта" value={config.support.useProjectDocs} onChange={v=>setConfig({...config,support:{...config.support,useProjectDocs:v}})}/><Switch label="Отвечать на вопросы о продукте" value={config.support.answerProductQuestions} onChange={v=>setConfig({...config,support:{...config.support,answerProductQuestions:v}})}/><label className={label}>Ответ при эскалации<textarea rows={2} value={config.support.escalationText} onChange={e=>setConfig({...config,support:{...config.support,escalationText:e.target.value}})} className={area}/></label><div className="rounded-[12px] border border-white/[.07] p-3"><p className="text-[11px] font-semibold text-white">Добавить FAQ</p><input aria-label="Вопрос FAQ" value={faqQ} onChange={e=>setFaqQ(e.target.value)} placeholder="Вопрос" className={input}/><textarea aria-label="Ответ FAQ" rows={3} value={faqA} onChange={e=>setFaqA(e.target.value)} placeholder="Подтверждённый ответ" className={area}/><Button variant="secondary" size="sm" fullWidth disabled={!faqQ.trim()||!faqA.trim()||busy==='faq'} onClick={addFaq}><Plus size={14}/> Добавить</Button>{faqs.map(f=><div key={f.id} className="mt-2 flex items-start gap-2 rounded-[10px] bg-white/[.03] p-2.5"><div className="min-w-0 flex-1"><p className="text-[11px] font-medium text-white">{f.question}</p><p className="mt-1 line-clamp-2 text-[10px] text-[#777780]">{f.answer}</p></div><button type="button" aria-label="Удалить FAQ" onClick={()=>delFaq(f.id)} className="flex h-11 w-11 cursor-pointer items-center justify-center text-red-300"><Trash2 size={14}/></button></div>)}</div></div></Section>

  <Section help="research" icon={<Globe2 size={18}/>} title="Интернет-ресерч" summary={config.research.mode==='off'?'Выключен':config.research.mode==='deep'?'Глубокий':'При необходимости'}><div className="space-y-4"><label className={label}>Режим<select value={config.research.mode} onChange={e=>setConfig({...config,research:{...config.research,mode:e.target.value}})} className={input}><option value="off">Выключен</option><option value="when_needed">При необходимости</option><option value="deep">Глубокий</option></select></label><Switch label="Показывать источники" value={config.research.showSources} onChange={v=>setConfig({...config,research:{...config.research,showSources:v}})}/><label className={label}>Исследований в сутки<input type="number" min={0} max={200} value={config.research.dailyLimit} onChange={e=>setConfig({...config,research:{...config.research,dailyLimit:Number(e.target.value)}})} className={input}/></label></div></Section>

  <Section help="replies" icon={<MessageCircle size={18}/>} title="Ответы и лимиты" summary="Reply, упоминания и вопросы о продукте"><div className="space-y-3"><Switch label="Отвечать на reply" value={config.replies.replyToDirectReply} onChange={v=>setConfig({...config,replies:{...config.replies,replyToDirectReply:v}})}/><Switch label="Отвечать на упоминания" value={config.replies.replyToMention} onChange={v=>setConfig({...config,replies:{...config.replies,replyToMention:v}})}/><Switch label="Распознавать вопросы о продукте" value={config.replies.replyToProductQuestion} onChange={v=>setConfig({...config,replies:{...config.replies,replyToProductQuestion:v}})}/><Switch label="Участвовать в обычной беседе" description="По умолчанию выключено" value={config.replies.ambientConversation} onChange={v=>setConfig({...config,replies:{...config.replies,ambientConversation:v}})}/><div className="grid grid-cols-2 gap-3"><label className={label}>Ответов в час<input type="number" value={config.limits.maxRepliesPerHour} onChange={e=>setConfig({...config,limits:{...config.limits,maxRepliesPerHour:Number(e.target.value)}})} className={input}/></label><label className={label}>Ответов в сутки<input type="number" value={config.limits.maxRepliesPerDay} onChange={e=>setConfig({...config,limits:{...config.limits,maxRepliesPerDay:Number(e.target.value)}})} className={input}/></label><label className={label}>Тишина с<input type="number" min={0} max={23} value={config.limits.quietFrom} onChange={e=>setConfig({...config,limits:{...config.limits,quietFrom:Number(e.target.value)}})} className={input}/></label><label className={label}>Тишина до<input type="number" min={0} max={23} value={config.limits.quietTo} onChange={e=>setConfig({...config,limits:{...config.limits,quietTo:Number(e.target.value)}})} className={input}/></label></div></div></Section>

  <Section help="activities" icon={<Activity size={18}/>} title="Активности" summary="Обсуждение, опрос и дайджест"><label className={label}>Тема<input value={activityTopic} onChange={e=>setActivityTopic(e.target.value)} className={input} placeholder="Оставьте пустым — CM выберет сам"/></label><div className="mt-3 grid grid-cols-3 gap-2">{[['DISCUSSION','Тема'],['POLL','Опрос'],['DIGEST','Дайджест']].map(([type,text])=><button type="button" key={type} onClick={()=>runActivity(type)} disabled={busy==='activity'||!m.enabled} className="min-h-11 cursor-pointer rounded-[11px] border border-white/[.08] px-2 text-[10px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{text}</button>)}</div></Section>

  <Section help="simulator" icon={<FlaskConical size={18}/>} title="Симулятор" summary="Проверить решение до применения"><textarea rows={4} value={simText} onChange={e=>setSimText(e.target.value)} className={area} placeholder="Сообщение участника"/><Button variant="secondary" size="sm" fullWidth disabled={busy==='simulate'||simText.trim().length<3} onClick={simulate}>{busy==='simulate'?<Loader2 size={14} className="animate-spin"/>:<><FlaskConical size={14}/> Проверить</>}</Button>{simulation&&<div className="mt-3 rounded-[11px] border border-white/[.07] bg-white/[.03] p-3"><p className="text-[11px] font-semibold text-white">{simulation.decision.respond?'Ответить':'Промолчать'} · {Math.round(simulation.decision.confidence*100)}%</p><p className="mt-1 text-[10px] text-[#777780]">{simulation.decision.intent} · {simulation.decision.reason}</p>{simulation.knowledge?.map((x:any,i:number)=><p key={i} className="mt-2 text-[10px] text-[#A1A1AA]">{x.source}: {x.text}</p>)}</div>}</Section>

  <Section help="log" icon={<MessageCircle size={18}/>} title="Журнал" summary={actions.length?'Последнее: '+actions[0].decision:'Событий пока нет'}><div className="space-y-2">{actions.length===0&&<p className="text-[11px] text-[#777780]">После запуска здесь появятся ответы, черновики и причины молчания.</p>}{actions.map(a=><div key={a.id} className="rounded-[11px] border border-white/[.07] bg-white/[.025] p-3"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-semibold text-white">{a.decision} · {a.intent||'—'}</p><span className="text-[9px] text-[#66666E]">{new Date(a.createdAt).toLocaleString('ru')}</span></div>{a.reason&&<p className="mt-1 text-[10px] text-[#777780]">{a.reason}</p>}{a.response&&<p className="mt-2 line-clamp-4 text-[11px] leading-relaxed text-[#D4D4D8]">{a.response}</p>}{a.decision==='DRAFT'&&<button type="button" onClick={()=>sendDraft(a.id)} className="mt-2 flex min-h-11 cursor-pointer items-center gap-2 rounded-[9px] bg-[rgba(255,106,0,.12)] px-3 text-[10px] font-semibold text-[#FF8A3D]"><Send size={13}/> Отправить</button>}</div>)}</div></Section>

  {message&&<p role="status" className="rounded-[12px] border border-white/[.07] bg-white/[.03] px-3 py-2.5 text-[11px] text-[#A1A1AA]">{message}</p>}
  <div className="sticky bottom-2 z-20 grid grid-cols-2 gap-2 rounded-[15px] border border-white/[.08] bg-[#0B0B0D]/95 p-2 backdrop-blur"><Button variant="secondary" size="sm" fullWidth disabled={busy==='save'||busy==='apply'} onClick={()=>save(false)}>{busy==='save'?<Loader2 size={14} className="animate-spin"/>:<><Save size={14}/> Сохранить</>}</Button><Button variant="primary" size="sm" fullWidth disabled={busy==='save'||busy==='apply'} onClick={()=>save(true)}>{busy==='apply'?<Loader2 size={14} className="animate-spin"/>:<><Check size={14}/> Применить</>}</Button></div>
 </div>
}