import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const repo = path.resolve(root, '..');
const require = createRequire(import.meta.url);
const { matchRegexWithTimeout } = require(path.join(root, 'dist/moderator/regexGuard.js'));
const { initiativeBackoffHours, consecutiveIgnored, chooseActivityType, chooseAdaptiveActivityType, chooseActivityTopic } = require(path.join(root, 'dist/communityManager/activityPolicy.js'));
const { rankKnowledge, documentChunks } = require(path.join(root, 'dist/communityManager/knowledgeSearch.js'));
const { actionPresentation } = require(path.join(root, 'dist/communityManager/actionPresentation.js'));
const { canRetryJob, retryDelayMs } = require(path.join(root, 'dist/communityManager/jobPolicy.js'));
const { acceptableInterventionResponse, moderatorFallback, responseSimilarity } = require(path.join(root, 'dist/moderator/interventionResponse.js'));
const { shouldJoinAmbient } = require(path.join(root, 'dist/communityManager/responsePolicy.js'));
const { allowConversationGreeting, needsNaturalConversationRewrite, sanitizeConversationReply } = require(path.join(root, 'dist/communityManager/conversationStyle.js'));
const { parseCommunityManagerConfig, randomInitiativeDate } = require(path.join(root, 'dist/communityManager/config.js'));
const { applyConversationPolicy, canJoinThematicConversation, isAddressedToCommunityManager, participationDecisionContext } = require(path.join(root, 'dist/communityManager/conversationIntelligence.js'));
const { personalityPrompt } = require(path.join(root, 'dist/communityManager/personality.js'));
const { interventionCooldownSeconds, selectRepeatedParticipant } = require(path.join(root, 'dist/moderator/interventionPolicy.js'));
const { normalizePostBlocks, blocksToPlainText, blocksToRichHtml } = require(path.join(root, 'dist/lib/richPost.js'));

assert.equal(initiativeBackoffHours(6, 0), 6);
assert.equal(initiativeBackoffHours(6, 1), 24);
assert.equal(initiativeBackoffHours(6, 2), 72);
assert.equal(initiativeBackoffHours(6, 3), 168);
assert.equal(consecutiveIgnored([{ automatic: true, evaluated: true, engaged: false }, { automatic: true, evaluated: true, engaged: false }, { automatic: true, evaluated: true, engaged: true }]), 2);
assert.equal(chooseActivityType(['DISCUSSION','POLL','GAME'], ['DISCUSSION']), 'POLL');
assert.equal(chooseAdaptiveActivityType(['DISCUSSION','POLL'], [{type:'DISCUSSION',evaluated:true,engaged:false}]), 'POLL');
assert.equal(chooseActivityTopic(['BTC','Prediction'], ['BTC']), 'Prediction');
assert.equal(canRetryJob(2), true);
assert.equal(canRetryJob(3), false);
assert.equal(retryDelayMs(1), 15000);
const legacyCmConfig = parseCommunityManagerConfig({identity:{displayName:'Test',role:'CM',bio:'Bio',tone:'friendly',addressForm:'ты'},activities:{silenceMinutes:60}});
assert.deepEqual(legacyCmConfig.identity.socialRoles, ['Свой человек','Помощник новичков']);
assert.equal(legacyCmConfig.activities.silenceMinMinutes, 40);
assert.equal(legacyCmConfig.activities.silenceMaxMinutes, 80);
assert.equal(randomInitiativeDate(legacyCmConfig,new Date('2026-07-15T00:00:00Z'),()=>0).toISOString(),'2026-07-15T00:40:00.000Z');
assert.equal(randomInitiativeDate(legacyCmConfig,new Date('2026-07-15T00:00:00Z'),()=>.999).toISOString(),'2026-07-15T01:20:00.000Z');
const conversationDecision={intent:'conversation',respond:true,research:false,confidence:.9,reason:'useful',engagementLevel:'contribute',conversationScore:.75,topic:'рынок',valueAdd:'контраргумент',moderatorFollowup:false,usage:{input:0,output:0}};
assert.equal(canJoinThematicConversation({config:{...legacyCmConfig,replies:{...legacyCmConfig.replies,ambientConversation:true,thematicConversation:true,participationLevel:'selective'}},decision:conversationDecision,participantCount:2,messageCount:4,cooldownFree:true}),true);
assert.equal(canJoinThematicConversation({config:{...legacyCmConfig,replies:{...legacyCmConfig.replies,ambientConversation:true,thematicConversation:true,participationLevel:'quiet'}},decision:conversationDecision,participantCount:2,messageCount:4,cooldownFree:true}),false);
const activeCmConfig={...legacyCmConfig,identity:{...legacyCmConfig.identity,displayName:'\u0410\u043b\u0435\u043a\u0441',socialRoles:['\u0417\u0430\u0432\u043e\u0434\u0438\u043b\u0430','\u0421\u0432\u043e\u0439 \u0447\u0435\u043b\u043e\u0432\u0435\u043a'],debateStyle:'fact_check'},replies:{...legacyCmConfig.replies,ambientConversation:true,thematicConversation:true,moderatorFollowups:true,participationLevel:'active'}};
assert.equal(isAddressedToCommunityManager('\u041a\u041c, \u043c\u0435\u043d\u044f \u0442\u0443\u0442 \u043e\u0431\u0438\u0436\u0430\u044e\u0442',activeCmConfig),true);
assert.equal(isAddressedToCommunityManager('\u0410\u043b\u0435\u043a\u0441, \u0442\u044b \u0447\u0435\u0433\u043e \u043c\u043e\u043b\u0447\u0438\u0448\u044c?',activeCmConfig),true);
assert.equal(isAddressedToCommunityManager('\u043e\u0431\u0441\u0443\u0436\u0434\u0430\u0435\u043c \u0438\u043d\u0434\u0435\u043a\u0441 \u0441\u0442\u0440\u0430\u0445\u0430',activeCmConfig),false);
assert.match(participationDecisionContext(activeCmConfig),/Participation level: active/);
const ignoredConflict={...conversationDecision,respond:false,engagementLevel:'ignore',conversationScore:.1,valueAdd:'',moderatorFollowup:false};
const socialDecision=applyConversationPolicy({config:activeCmConfig,decision:ignoredConflict,text:'\u041a\u041c, \u043c\u0435\u043d\u044f \u0442\u0443\u0442 \u043e\u0431\u0438\u0436\u0430\u044e\u0442',socialAddress:true,recentModerator:true,participantCount:4,messageCount:12});
assert.equal(socialDecision.respond,true);
assert.equal(socialDecision.moderatorFollowup,true);
assert.equal(socialDecision.engagementLevel,'contribute');
const unsafeDecision=applyConversationPolicy({config:activeCmConfig,decision:{...ignoredConflict,intent:'unsafe'},text:'CM unsafe request',socialAddress:true,recentModerator:true,participantCount:4,messageCount:12});
assert.equal(unsafeDecision.respond,false);
assert.equal(unsafeDecision.moderatorFollowup,false);
assert.match(personalityPrompt({...legacyCmConfig,identity:{...legacyCmConfig.identity,profanityLevel:'rough',debateStyle:'provoke'}}),/never use slurs/i);
assert.equal(actionPresentation({decision:'RESPOND',intent:'conversation',metadata:{engagementLevel:'contribute',conversationScore:.82,thematic:true}}).engagementLabel,'Добавить по существу');
assert.equal(documentChunks('Раздел один с достаточно длинным содержанием для индексации и проверки поиска.').length, 1);
assert.equal(rankKnowledge('комиссия вывода', [{source:'FAQ',text:'Комиссия за вывод составляет один процент',priority:5}])[0].source, 'FAQ');
assert.equal(actionPresentation({decision:'SILENT',intent:'limits',reason:'Quiet hours or quota'}).decisionLabel, 'Промолчал');
assert.equal(acceptableInterventionResponse('Если есть вопросы по BTC, задавайте.', []), false);
assert.ok(responseSimilarity('Без личных оскорблений, пожалуйста', 'Пожалуйста, без личных оскорблений') > .68);
assert.ok(moderatorFallback('conflict', [], 1).length > 10);
assert.equal(interventionCooldownSeconds(300), 300);
assert.equal(selectRepeatedParticipant('u2',['u1','u2'],['u1','u2'],['u1','u2']), 'u2');
assert.equal(selectRepeatedParticipant('u3',['u1'],['u1','u2'],['u1','u2','u3']), 'u1');
assert.equal(shouldJoinAmbient({enabled:true,intent:'conversation',respond:true,confidence:.8,hasQuestion:true,textLength:16}), true);
assert.equal(shouldJoinAmbient({enabled:true,intent:'conversation',respond:true,confidence:.8,hasQuestion:false,textLength:10}), false);
assert.equal(shouldJoinAmbient({enabled:true,intent:'unsafe',respond:true,confidence:.9,hasQuestion:true,textLength:40}), false);
assert.equal(allowConversationGreeting('Привет, подскажешь?', false), true);
assert.equal(allowConversationGreeting('Привет ещё раз', true), false);
assert.equal(allowConversationGreeting('Ответ будет', false), false);
assert.equal(sanitizeConversationReply('Привет! Давай разбираться. По BTC всё без изменений.', false), 'По BTC всё без изменений.');
assert.equal(needsNaturalConversationRewrite('Что именно интересует? Если есть конкретный вопрос — пиши.'), true);
assert.equal(sanitizeConversationReply('По BTC всё без изменений. Если есть конкретный вопрос — пиши.', false), 'По BTC всё без изменений.');
assert.equal(needsNaturalConversationRewrite('Будет, куда он денется.'), false);
const legacyBlocks = normalizePostBlocks([{ type: 'list', ordered: false, items: [[{ t: 'Legacy item', b: true }], [{ t: 'Second item' }]] }]);
assert.deepEqual(legacyBlocks?.[0]?.items?.[0], { runs: [{ t: 'Legacy item', b: true }] });
assert.match(blocksToPlainText(legacyBlocks), /Legacy item/);
assert.match(blocksToRichHtml(legacyBlocks), /Legacy item/);
assert.deepEqual(normalizePostBlocks([{ type: 'image', url: 'https://example.com/a.jpg', prompt: 'keep me' }])?.[0], { type: 'image', url: 'https://example.com/a.jpg', prompt: 'keep me' });

assert.equal(await matchRegexWithTimeout(['spam\\d+'], 'prefix spam42 suffix'), 'spam\\d+');
const started = Date.now();
assert.equal(await matchRegexWithTimeout(['^(a+)+$'], 'a'.repeat(4095) + '!', 100), null);
assert.ok(Date.now() - started < 500, 'catastrophic regex escaped its worker timeout');

const lock = JSON.parse(fs.readFileSync(path.join(root, 'package-lock.json'), 'utf8'));
const multerVersion = lock.packages?.['node_modules/multer']?.version;
const [major, minor] = String(multerVersion).split('.').map(Number);
assert.ok(major > 2 || (major === 2 && minor >= 2), `unsafe multer version: ${multerVersion}`);

const dockerfile = fs.readFileSync(path.join(root, 'Dockerfile'), 'utf8');
assert.match(dockerfile, /FROM node:20-bookworm-slim AS runtime/);
assert.match(dockerfile, /USER node/);
const caddyfile = fs.readFileSync(path.join(repo, 'deploy/Caddyfile'), 'utf8');
assert.match(caddyfile, /Content-Security-Policy/);
assert.match(caddyfile, /max_size 32MB/);

console.log('security smoke: ok');